const dataProduk = [
 { id: 1,
   name: "Hp Advan X1 | 8/128gb Mediatek Helio G100 120hz", 
   price: 1999, rating: 4.9, sold: 4400, type: "Mall",
   link: "https://s.shopee.co.id/40d3y3WBPN",
   vid: null },
 { id: 2,
   name: "Kaca Cermin Gantung 30 & 40cm", 
   price: 70, rating: 4.9, sold: 4000, type: "Mall",
   link: "https://s.shopee.co.id/8AScyQW7YO",
   vid: null },
 { id: 3,
   name: "Alat Penghilang Bulu Pakaian 6 Pisau 2 in 1", 
   price: 97, rating: 4.8, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/50VbCmds0X",
   vid: null },
 { id: 4,
   name: "Jaket Hoodie Bomber Pria Berkerudung Flace Musim Dingin Tebal Hangat", 
   price: 190, rating: 4.8, sold: 2000, type: "Star",
   link: "https://s.shopee.co.id/8fOtbW7mxi",
   vid: null },
 { id: 5,
   name: "Cermin Akrilik Anti Pecah & Lentur Tempel Dinding", 
   price: 76, rating: 4.8, sold: 4000, type: "Mall",
   link: "https://s.shopee.co.id/BQLUIPeIk",
   vid: null },
 { id: 6,
   name: "Face Wash SOMBONG 5 in 1 With Coffee & Ginsen Sabun Pembersih Wajah 100ml", 
   price: 39, rating: 4.9, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/8fOtcAcExI",
   vid: null },
 { id: 7,
   name: "Kipas Portable Goojodoq Turbo 100 Gear Wind High Speed", 
   price: 138, rating: 4.9, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/9KeaPWfgNl",
   vid: null },
 { id: 8,
   name: "Rak Susun Serbaguna 4 Tingkat Portable Berbahan Plastik", 
   price: 29, rating: 4.8, sold: 8000, type: "Mall",
   link: "https://s.shopee.co.id/4AwUGCv7AD",
   vid: null },
 { id: 9,
   name: "Obeng Set Lengkap Kunci Shock Set Screwdriver Racket Toolkit", 
   price: 130, rating: 4.9, sold: 2000, type: "Mall",
   link: "https://s.shopee.co.id/4qCB6GOBAk",
   vid: null },
 { id: 10,
   name: "Tool Box 85 Pcs Kunci Shock Set Otomotif Alat Bengkel", 
   price: 1128, rating: 4.8, sold: 1000, type: "Mall",
   link: "https://s.shopee.co.id/4fskuBQNQ6",
   vid: null },
 { id: 11,
   name: "Lemari Pakaian Minimalist 2 Pintu - LUNA LP 2P", 
   price: 533, rating: 4.9, sold: 4000, type: "Mall",
   link: "https://s.shopee.co.id/AADhSfr4Lu",
   vid: null },
 { id: 12,
   name: "Jam Tangan Pria Wanita Digital Sport EL Backlight Tali Rubber Anti Air", 
   price: 164, rating: 4.8, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/1BIskNOQbr",
   vid: null },
 { id: 13,
   name: "Parfum Kahf Revered Oud Eau De Toilette 35ml Long-lasting Fragrance", 
   price: 111, rating: 4.9, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/1Vvj92qkHO",
   vid: null },
 { id: 14,
   name: "Jam Tangan Pria Analog Stainless Steel Chronograph Aktif Luminous Hand", 
   price: 346, rating: 4.8, sold: 8000, type: "Mall",
   link: "https://s.shopee.co.id/1gF9LcAnnm",
   vid: null },
 { id: 15,
   name: "Jam Tangan Pria Digital Anti Air Multifungsi", 
   price: 175, rating: 4.8, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/2VoGLI36Ik",
   vid: null },
 { id: 16,
   name: "Jam Tangan Pria Digital Analog Sport Watch Anti Air",
   price: 166, rating: 4.9, sold: 8000, type: "Mall",
   link: "https://s.shopee.co.id/9zuHHAkdYG",
   vid: null },
 { id: 17,
   name: "Jam Tangan Wanita Cloe Watch", 
   price: 188, rating: 4.9, sold: 3000, type: "Mall",
   link: "https://s.shopee.co.id/9KeaU5q08f",
   vid: null },
 { id: 18,
   name: "Jaket Zipper Hoodie Sweater Oversized Beruang Wanita - Pria", 
   price: 104, rating: 4.9, sold: 4000, type: "Mall",
   link: "https://s.shopee.co.id/2VoGLlqIKu",
   vid: null },
 { id: 19,
   name: "Sepatu Sneakers Wanita Shoes Fashion Korea", 
   price: 114, rating: 4.8, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/60O8WOujy8",
   vid: null },
 { id: 20,
   name: "White Dress Korean Fashion High Collar Design", 
   price: 127, rating: 4.8, sold: 800, type: "Mall",
   link: "https://s.shopee.co.id/50VbKjh6wn",
   vid: null },
 { id: 21,
   name: "Dress Fashion Korean High Class", 
   price: 124, rating: 4.8, sold: 3000, type: "Mall",
   link: "https://s.shopee.co.id/5Ap1X9LMXf",
   vid: null },
 { id: 22,
   name: "Dress Early Autum Fairy", 
   price: 190, rating: 4.9, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/LjlmPJDRC",
   vid: null },
 { id: 23,
   name: "Mini Dress Korean Vintage Formal", 
   price: 119, rating: 4.9, sold: 6000, type: "Mall",
   link: "https://s.shopee.co.id/3VgnYJijpc",
   vid: null },
 { id: 24,
   name: "Blazer Wanita / Jas Kantor Lengan Panjang Korean Style", 
   price: 149, rating: 4.8, sold: 1000, type: "Mall",
   link: "https://s.shopee.co.id/10zSZt5bof",
   vid: null },
 { id: 25,
   name: "Atasan Wanita Korean Style Kekinian Jaket Wanita", 
   price: 123, rating: 4.8, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/5L8Rk3O4Ij",
   vid: null },
 { id: 26,
   name: "Blazer Biru Tweed Blazer Wanita Crop Top Korean Style", 
   price: 157, rating: 4.9, sold: 3000, type: "Mall",
   link: "https://s.shopee.co.id/7Aa5vZUumg",
   vid: null },
 { id: 27,
   name: "Celana Pria Kargo Loose Pants Casual Original", 
   price: 152, rating: 4.8, sold: 5000, type: "Mall",
   link: "https://s.shopee.co.id/3B3xANxq7N",
   vid: null },
 { id: 28,
   name: "Cincin Wanita Original Sertifikat GRA Silver Goddess of Laurel", 
   price: 499, rating: 4.9, sold: 1000, type: "Mall",
   link: "https://s.shopee.co.id/9par6kRzMo",
   vid: null },
 { id: 29,
   name: "Cincin Couple Pria Wanita Original Sertifikat", 
   price: 737, rating: 4.8, sold: 930, type: "Mall",
   link: "https://s.shopee.co.id/901k7LrQzC",
   vid: null },
 { id: 30,
   name: "Cincin Wanita Original Sertifikat GRA Perak Starry Dream", 
   price: 409, rating: 5, sold: 1000, type: "Mall",
   link: "https://s.shopee.co.id/9fHQugQxoj",
   vid: null },
 { id: 31,
   name: "Tas Wanita / Tas Selempang Fashion Sling Bag Korean",
   price: 185, rating: 4.9, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/9fHQurPXrW",
   vid: null },
 { id: 32,
   name: "Tas Fashion Bag Petit Charm  Model Trendy Women", 
   price: 198, rating: 4.9, sold: 1000, type: "Mall",
   link: "https://s.shopee.co.id/4fskxnALO2",
   vid: null },
 { id: 33,
   name: "Sepatu Sneakers Wanita Premium Ringan Empuk Biru Putih Korean Style", 
   price: 146, rating: 4.9, sold: 6000, type: "Mall",
   link: "https://s.shopee.co.id/4fskxvyb2c",
   vid: null },
 { id: 34,
   name: "Gelang Wanita Berlian Original Heart Design", 
   price: 103, rating: 4.9, sold: 1000, type: "Mall",
   link: "https://s.shopee.co.id/1gF9OYGtJk",
   vid: null },
 { id: 35,
   name: "Tas Sekolah Korean Fashion Style Lucu", 
   price: 129, rating: 4.9, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/BQLbsj7kt",
   vid: null },
 { id: 36,
   name: "Sepatu Boots Fashion Wanita", 
   price: 299, rating: 4.9, sold: 9000, type: "Mall",
   link: "https://s.shopee.co.id/70GfkY0XWZ",
   vid: null },
 { id: 37,
   name: "Jam Tangan Wanita Anti Air Berlian", 
   price: 152, rating: 4.9, sold: 5000, type: "Mall",
   link: "https://s.shopee.co.id/7Aa5wyqtne",
   vid: null },
 { id: 38,
   name: "Tote Bag / Tas Fashion Wanita Mayonette", 
   price: 104, rating: 4.8, sold: 7000, type: "Mall",
   link: "https://s.shopee.co.id/1gF9Oz94uS",
   vid: null },
 { id: 39,
   name: "Tas Wanita Fashion Import Handbag", 
   price: 276, rating: 4.9, sold: 6000, type: "Mall",
   link: "https://s.shopee.co.id/2VoGOeWvEw",
   vid: null },
 { id: 40,
   name: "Dress Wanita Vintage Korean Style Cream Long Sleeve",
   price: 178, rating: 4.9, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/3B3xBybJHg ",
   vid: null },
 { id: 41,
   name: "Palu Multifungsi / Palu Tang Lipat Multifunctional Axe Hammer Survival Tools", 
   price: 135, rating: 4.8, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/7ppmkmsiwz",
   vid: null },
 { id: 42,
   name: "Set Pisau Dapur Utility Knife 5pcs Stainless Steel", 
   price: 127, rating: 4.9, sold: 2000, type: "Mall",
   link: "https://s.shopee.co.id/7fWMYfWucX",
   vid: null },
 { id: 43,
   name: "Tas Ransel Anak Perempuan Anti Air Model Korea Tebal", 
   price: 169, rating: 4.9, sold: 3000, type: "Mall",
   link: "https://s.shopee.co.id/3g0DnRuOAd",
   vid: null },
 { id: 44,
   name: "Jenny Pants Culottes Celana Panjang Wanita Highcwaist", 
   price: 189, rating: 4.9, sold: 4000, type: "Star",
   link: "https://s.shopee.co.id/W3C1nc5FF",
   vid: null },
 { id: 45,
   name: "Harvia Sendal Fashion Wanita Slip On 2 Strap Korean Look", 
   price: 195, rating: 4.9, sold: 2000, type: "Mall",
   link: "https://s.shopee.co.id/40d4CNPf2w",
   vid: null },
 { id: 46,
   name: "Powerbank Slim 10.000mah Dual Port Usb C & Usb A 15W PD 3.0 Quick Charge Portable", 
   price: 239, rating: 4.9, sold: 1000, type: "Mall",
   link: "https://s.shopee.co.id/20rztYpzqG",
   vid: null },
 { id: 47,
   name: "Tas Wanita Slingbag En-ji", 
   price: 379, rating: 4.9, sold: 1000, type: "Mall",
   link: "https://s.shopee.co.id/6fdpSS8PpC",
   vid: null },
 { id: 48,
   name: "Buku Quranic Law of Attraction Edisi Terbaru", 
   price: 175, rating: 4.9, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/10zSiTGT9M",
   vid: null },
 { id: 49,
   name: "Asahan Pisau & Gunting 3 Steps", 
   price: 73, rating: 4.8, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/AUqY2ZxYWb",
   vid: null },
 { id: 50,
   name: "Tas Ransel Anak Perempuan Ins Anti Air Model Korea Tebal - Aimilo", 
   price: 169, rating: 4.9, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/4VZKtfmVOB",
   vid: null },
 { id: 51,
   name: "Sabun Pembersih Sepatu Putih & Warna Suedecleaner", 
   price: 56, rating: 4.9, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/9parFct9rq",
   vid: null },
 { id: 52,
   name: "Sampo Penghilang Uban / Penghitam Rambut Original", 
   price: 89, rating: 4.9, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/8Km3T6lnTt",
   vid: null },
 { id: 53,
   name: "Senter LED Super Terang IPX4 Tahan Air Powerbank Multifungsi 45W 9600mah", 
   price: 228, rating: 4.8, sold: 5000, type: "Mall",
   link: "https://s.shopee.co.id/2VoGWZB3PE",
   vid: null },
 { id: 54,
   name: "Tas Sekolah Aesthetic Korean Style", 
   price: 95, rating: 4.8, sold: 2000, type: "Mall",
   link: "https://s.shopee.co.id/1gF9XHGxzU",
   vid: null },
 { id: 55,
   name: "Jaket Winter Jubah Wanita Panjang Tebal Hoddie Musim Dingin", 
   price: 175, rating: 4.9, sold: 1000, type: "Mall",
   link: "https://s.shopee.co.id/5VRs6StvSw",
   vid: null },
 { id: 56,
   name: "Rok Kerja Kuliah Wanita | Rok Wanita Korean Style", 
   price: 139, rating: 4.9, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/2BBQ8UyJVv",
   vid: null },
 { id: 57,
   name: "Jaket Kulit Wanita Coklat Hitam Faux Synthetic Leather Jacket Original", 
   price: 199, rating: 4.9, sold: 2000, type: "Mall",
   link: "https://s.shopee.co.id/AUqY3yK9NC",
   vid: null },
 { id: 58,
   name: "Set Tiga Potong Wanita Stretch Kasual Suspender Lengan Panjang | Pakaian Wanita", 
   price: 137, rating: 4.8, sold: 5000, type: "Mall",
   link: "https://s.shopee.co.id/9parGtOgpH",
   vid: null },
 { id: 59,
   name: "Piyama Kekinian Baju Tidur Wanita Piyama Lengan Panjang", 
   price: 120, rating: 4.8, sold: 2000, type: "Mall",
   link: "https://s.shopee.co.id/4AwUWc7lyQ",
   vid: null },
 { id: 60,
   name: "Set Korean Style Hijab | Set Pakaian Wanita", 
   price: 164, rating: 4.8, sold: 1000, type: "Mall",
   link: "https://s.shopee.co.id/LjlxhYwjU",
   vid: null },
 { id: 61,
   name: "Sepatu Sneakers Pria Premium Modis Tredny Modern PANARYBODY", 
   price: 215, rating: 4.9, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/6VKPJcKN0K",
   vid: null },
 { id: 62,
   name: "Kaos Pria Regular No Void Minds | Charcoal", 
   price: 89, rating: 4.9, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/4LFul6Q5ux",
   vid: null },
 { id: 63,
   name: "Jaket Bomber Pria House of Smith - Bomen Black", 
   price: 249, rating: 4.8, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/40d4MdsFcO",
   vid: null },
 { id: 64,
   name: "Celana Pria Formal Bahan Premium Black Slimpit", 
   price: 118, rating: 4.8, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/40d4MiTxRp",
   vid: null },
 { id: 65,
   name: "Celana Olahraga Pria Panjang Elastis Cepat Kering", 
   price: 109, rating: 4.8, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/6VKPLP9psy",
   vid: null },
 { id: 66,
   name: "Kaos Pria Oversized FORMLOCK No Void | Sand", 
   price: 94, rating: 4.9, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/7Aa68kHKG2",
   vid: null },
 { id: 67,
   name: "Celana Cargo Pria Long Pants Cotton Twill", 
   price: 110, rating: 4., sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/3LNNZqGK0P",
   vid: null },
 { id: 68,
   name: "Celana Kargo Pria Lembut Lurus Korean Style", 
   price: 156, rating: 4.8, sold: 6000, type: "Mall",
   link: "https://s.shopee.co.id/2VoGc2wHkB",
   vid: null },
 { id: 69,
   name: "Celana Chino Panjang Reguler Standar Straight Fit", 
   price: 100, rating: 4.8, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/6fdpYAkDdj",
   vid: null },
 { id: 70,
   name: "Jaket Pria Waterproof Tebal Warna Hitam", 
   price: 138, rating: 4.8, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/1gF9b6HTVL",
   vid: null },
 { id: 71,
   name: "Jaket Parasut Pria Windbreakers Outdor Waterproof Bahan Taslan Premium", 
   price: 179, rating: 4.9, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/BQLoQq6KR",
   vid: null },
 { id: 72,
   name: "Tas Ransel Backpack Pria Waterproof", 
   price: 193, rating: 4.9, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/8ASdMXUyrV",
   vid: null },
 { id: 73,
   name: "Tas Ransel Gunung Backpack Carrier Hiking Camping 40L", 
   price: 257, rating: 4.8, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/5L8RzQn2KY",
   vid: null },
 { id: 74,
   name: "Sepatu Sneakers Mono Series Gray", 
   price: 270, rating: 4.9, sold: 599, type: "Mall",
   link: "https://s.shopee.co.id/5VRsBqoJl6",
   vid: null },
 { id: 75,
   name: "Absolute Jaket Leather Sintetis Baseball", 
   price: 184, rating: 4.9, sold: 2000, type: "Mall",
   link: "https://s.shopee.co.id/6fdpaC7yFe",
   vid: null },
 { id: 76,
   name: "Tas Ransel Canvas Molypack Backpack", 
   price: 295, rating: 4.9, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/4qCBP0Nm5c",
   vid: null },
 { id: 77,
   name: "Sepatu Sneakers Lokal UMBRELLA White Maroon", 
   price: 260, rating: 4.9, sold: 3000, type: "Mall",
   link: "https://s.shopee.co.id/gMcRUR8JV",
   vid: null },
 { id: 78,
   name: "Kaos Oversized Heavyweight Cotton 16s Jumbo Tebal", 
   price: 163, rating: 4.9, sold: 1000, type: "Mall",
   link: "https://s.shopee.co.id/1VvjR8Gs3O",
   vid: null },
 { id: 79,
   name: "Kacamata Bulat Metal Lensa Minus Anti Radiasi Bluechromic Pria Wanita", 
   price: 152, rating: 4.9, sold: 1000, type: "Mall",
   link: "https://s.shopee.co.id/6fdpats3Md",
   vid: null },
 { id: 80,
   name: "Kacamata Minus Photochromic Wanita Anti Radiasi Blueray UV400 Frame 2 in 1", 
   price: 119, rating: 4.8, sold: 5000, type: "Mall",
   link: "https://s.shopee.co.id/qg2eTs51H",
   vid: null },
 { id: 81,
   name: "Sepatu Hiking Outdoor Sneakers Pria Wanita Gunung Boots Anti Slip", 
   price: 227, rating: 4.8, sold: 5000, type: "Mall",
   link: "https://s.shopee.co.id/9Uy0yx8JaF",
   vid: null },
 { id: 82,
   name: "Jaket Catania Outdoor Wanita Pria", 
   price: 220, rating: 4.8, sold: 9000, type: "Mall",
   link: "https://s.shopee.co.id/1LcL46rjem",
   vid: null },
 { id: 83,
   name: "Lorica Jaket Bomber Wanita", 
   price: 189, rating: 4.9, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/5q4kQUbyCs",
   vid: null },
 { id: 84,
   name: "Sabrina Jaket Wanita Bolak Balik", 
   price: 223, rating: 4.9, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/9ALCOgwvmk",
   vid: null },
 { id: 85,
   name: "Jaket Hoddie Fleece Unisek | Los Angeles - Nyaman Hangat Tampil Stylish", 
   price: 273, rating: 4.9, sold: 300, type: "Mall",
   link: "https://s.shopee.co.id/6pxHcXkzYq",
   vid: null },
 { id: 86,
   name: "Sweater Crewneck Fleece Katun Tebal", 
   price: 159, rating: 4.9, sold: 570, type: "Mall",
   link: "https://s.shopee.co.id/BQNgRphBV",
   vid: null },
 { id: 87,
   name: "Tas Ransel Wanita Ringan Anti Air Apricot Hitam", 
   price: 269, rating: 4.9, sold: 200, type: "Mall",
   link: "https://s.shopee.co.id/W3E5CnbrK",
   vid: null },
 { id: 88,
   name: "Jaket Sukajan Shinigami Embroidery Two in One", 
   price: 171, rating: 4.9, sold: 2000, type: "Mall",
   link: "https://s.shopee.co.id/7fWOcWGM06",
   vid: null },
 { id: 89,
   name: "Jaket Denim Wanita Oversized Bigmouse", 
   price: 155, rating: 4.8, sold: 6000, type: "Mall",
   link: "https://s.shopee.co.id/3Vgpf0vSBU",
   vid: null },
 { id: 90,
   name: "Jam Tangan Wanita Analog", 
   price: 195, rating: 4.9, sold: 2000, type: "Mall",
   link: "https://s.shopee.co.id/AUqZzytGEq",
   vid: null },
 { id: 91,
   name: "Tas Ransel Pria Mode Bru Kasual Tahan Air", 
   price: 178, rating: 4.9, sold: 1000, type: "Mall",
   link: "https://s.shopee.co.id/5L8TqfPfnU",
   vid: null },
 { id: 92,
   name: "Kaos Oversized Lengan Pendek Tiga Garis Korea", 
   price: 82, rating: 4.8, sold: 6000, type: "Star",
   link: "https://s.shopee.co.id/9fHT1N4H7a",
   vid: null },
 { id: 93,
   name: "SOPHIA Bodysuit Wanita | Atasan Wanita Lengan Panjang", 
   price: 88, rating: 4.9, sold: 10000, type: "Star",
   link: "https://s.shopee.co.id/9ALCQgjPkD",
   vid: null },
 { id: 94,
   name: "Kaos Distro Pria 210gsm Blok Logo Silver Lengan Pendek", 
   price: 110, rating: 4.8, sold: 10000, type: "Star",
   link: "https://s.shopee.co.id/2qR8t7jv2R",
   vid: null },
 { id: 95,
   name: "Kaos Oversized Lengan Pendek Tiga Garis Korea", 
   price: 82, rating: 4.9, sold: 1000, type: "Star",
   link: "https://s.shopee.co.id/4VZMsLKTm2",
   vid: null },
 { id: 96,
   name: "Washing Tshirt Riot Black 24s", 
   price: 83, rating: 4.8, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/6VKRGEGLRL",
   vid: null },
 { id: 97,
   name: "Kaos Couple Oversized Wo & Men Mandarin Karakter", 
   price: 79, rating: 4.8, sold: 4000 , type: "Mall",
   link: "https://s.shopee.co.id/9fHT28HSjy",
   vid: null },
 { id: 98,
   name: "Korean Loose Maxi Skirt Rok Wanita Anti Kusut Polyester - Rok Flare Scuba Wanita", 
   price: 80, rating: 4.9, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/2g7ihRg8tH",
   vid: null },
 { id: 99,
   name: "Rok Shena Span Panjang 103cm Bawahan Rok Highwaist Kantor Scuba Wanita", 
   price: 145, rating: 4.9, sold: 10000, type: "Mall",
   link: "https://s.shopee.co.id/3LNPUoEB0g",
   vid: null },
 { id: 100,
   name: "Atasan Wanita Korean Blouse Top Rupple", 
   price: 79, rating: 4.9, sold: 6000, type: "Mall",
   link: "https://s.shopee.co.id/7Aa84TB742",
   vid: null }
];
