var idiomData = [
{
  "name": "Idiom",
  "items": [
    { "word": "Money grubber", "pronounce": "ma-ni gra-ber", "def": "Mata duitan", "ex": "He's a real money grubber." },
    { "word": "Money talks", "pronounce": "ma-ni toks", "def": "Uang bisa mengatur segalanya", "ex": "In business, money talks." },
    { "word": "Move the goalposts", "pronounce": "muv the gol-posts", "def": "Mengubah aturan di tengah jalan", "ex": "Stop moving the goalposts!" },
    { "word": "Night owl", "pronounce": "nait aul", "def": "Suka bergadang", "ex": "I'm a night owl." },
    { "word": "No sweat", "pronounce": "no swet", "def": "Tidak masalah", "ex": "No sweat, I can do it." },
    { "word": "To talk through one's hat", "pronounce": "tu tok thru wans hat", "def": "Bicara omong kosong", "ex": "He's talking through his hat." },
    { "word": "Nothing to write home about", "pronounce": "na-thing tu rait hom a-baut", "def": "Tidak ada yang istimewa", "ex": "The food is nothing to write home about." },
    { "word": "Off the hook", "pronounce": "of the huk", "def": "Lepas dari masalah", "ex": "You're off the hook this time." },
    { "word": "On cloud nine", "pronounce": "on klaud nain", "def": "Sangat bahagia", "ex": "She's on cloud nine after the news." },
    { "word": "On the ball", "pronounce": "on the bol", "def": "Cekatan", "ex": "You're really on the ball today." },
    { "word": "On the fence", "pronounce": "on the fens", "def": "Ragu-ragu", "ex": "I'm still on the fence about it." },
    { "word": "On thin ice", "pronounce": "on thin ais", "def": "Dalam posisi berisiko", "ex": "You're on thin ice with that behavior." },
    { "word": "Once in a while", "pronounce": "wans in a wail", "def": "Sesekali", "ex": "I go to the cinema once in a while." },
    { "word": "Open a can of worms", "pronounce": "o-pen a kan of werms", "def": "Membuka masalah baru", "ex": "Don't open a can of worms." },
    { "word": "Out of line", "pronounce": "aut of lain", "def": "Tidak sopan", "ex": "That remark was out of line." },
    { "word": "Out of shape", "pronounce": "aut of sheyp", "def": "Tidak fit", "ex": "I'm really out of shape." },
    { "word": "Out of the blue", "pronounce": "aut of the blu", "def": "Tiba-tiba", "ex": "He called me out of the blue." },
    { "word": "Out of your league", "pronounce": "aut of yor lig", "def": "Di luar kemampuanmu", "ex": "He's out of your league." },
    { "word": "Pass the buck", "pronounce": "pas the bak", "def": "Lempar tanggung jawab", "ex": "Don't pass the buck." },
    { "word": "A blessing in disguise", "pronounce": "a ble-sing in dis-gaiz", "def": "Keuntungan dari musibah", "ex": "Losing that job was a blessing in disguise." },
    { "word": "A dime a dozen", "pronounce": "a daim a da-zen", "def": "Murah dan berlimpah", "ex": "Coffee shops are a dime a dozen here." },
    { "word": "A piece of cake", "pronounce": "a pis of keyk", "def": "Sangat mudah", "ex": "The exam was a piece of cake." },
    { "word": "Actions speak louder than words", "pronounce": "ak-syens spik lau-der than werds", "def": "Bukti lebih kuat dari kata-kata", "ex": "Actions speak louder than words." },
    { "word": "Add insult to injury", "pronounce": "ad in-salt tu in-ju-ri", "def": "Memperburuk keadaan", "ex": "He added insult to injury by laughing." },
    { "word": "All ears", "pronounce": "ol irs", "def": "Mendengarkan dengan saksama", "ex": "I'm all ears." },
    { "word": "An arm and a leg", "pronounce": "an arm and a leg", "def": "Harga yang sangat mahal", "ex": "The car cost an arm and a leg." },
    { "word": "Apple of my eye", "pronounce": "a-pel of mai ai", "def": "Kesayangan", "ex": "She's the apple of my eye." },
    { "word": "Back to the drawing board", "pronounce": "bak tu the dro-ing bord", "def": "Mulai lagi dari awal", "ex": "It failed, so back to the drawing board." },
    { "word": "Barking up the wrong tree", "pronounce": "bar-king ap the rong tri", "def": "Salah sasaran", "ex": "You're barking up the wrong tree." }
  ]
},{
  "name": "Idiom 2",
  "items": [
    { "word": "Pins and needles", "pronounce": "pins and ni-dels", "def": "Kesemutan", "ex": "I have pins and needles in my foot." },
    { "word": "Play favorites", "pronounce": "pley fey-vor-its", "def": "Pilih kasih", "ex": "Don't play favorites." },
    { "word": "Play it cool", "pronounce": "pley it kul", "def": "Tetap tenang", "ex": "Just play it cool." },
    { "word": "Play with fire", "pronounce": "pley with fai-yer", "def": "Bermain bahaya", "ex": "You're playing with fire." },
    { "word": "Pull a fast one", "pronounce": "pul a fast wan", "def": "Menipu", "ex": "He pulled a fast one." },
    { "word": "Pull some strings", "pronounce": "pul sam strings", "def": "Gunakan koneksi", "ex": "He pulled some strings to get the job." },
    { "word": "Pull someone's leg", "pronounce": "pul sam-wans leg", "def": "Bercanda dengan seseorang", "ex": "Stop pulling my leg!" },
    { "word": "Pull yourself together", "pronounce": "pul yor-self to-ge-ther", "def": "Tenangkan diri", "ex": "You need to pull yourself together." },
    { "word": "Put on the spot", "pronounce": "put on the spot", "def": "Membuat tidak nyaman", "ex": "You put me on the spot." },
    { "word": "Put two and two together", "pronounce": "put tu and tu to-ge-ther", "def": "Menyimpulkan sendiri", "ex": "I put two and two together." },
    { "word": "Rain on someone's parade", "pronounce": "reyn on sam-wans pa-reyd", "def": "Merusak suasana", "ex": "Don't rain on my parade." },
    { "word": "Raise the bar", "pronounce": "reyz the bar", "def": "Meningkatkan standar", "ex": "They raised the bar." },
    { "word": "Read between the lines", "pronounce": "rid bi-twin the lainz", "def": "Membaca maksud tersembunyi", "ex": "Read between the lines." },
    { "word": "Rock the boat", "pronounce": "rok the bot", "def": "Membuat kekacauan", "ex": "Don't rock the boat." },
    { "word": "Rub it in", "pronounce": "rab it in", "def": "Mengungkit-ungkit", "ex": "Stop rubbing it in." },
    { "word": "Rule of thumb", "pronounce": "rul of tham", "def": "Aturan umum", "ex": "As a rule of thumb, save 10%." },
    { "word": "Scratch one's head", "pronounce": "skrach wans hed", "def": "Berpikir keras", "ex": "I scratched my head in confusion." },
    { "word": "See eye to eye", "pronounce": "si ai tu ai", "def": "Sepakat", "ex": "We don't see eye to eye." },
    { "word": "Shake a leg", "pronounce": "sheyk a leg", "def": "Cepat sedikit", "ex": "Shake a leg! We're late." },
    { "word": "Shoot the breeze", "pronounce": "shut the briz", "def": "Ngobrol santai", "ex": "We shot the breeze all afternoon." },
    { "word": "Sit tight", "pronounce": "sit tait", "def": "Tunggu dengan sabar", "ex": "Sit tight, I'll be right back." },
    { "word": "Sleep on it", "pronounce": "slip on it", "def": "Pikirkan dulu", "ex": "I'll sleep on it." },
    { "word": "Chew the fat", "pronounce": "chu the fat", "def": "Basa-basi", "ex": "We chewed the fat for an hour." },
    { "word": "Smash hit", "pronounce": "smash hit", "def": "Sukses besar", "ex": "The song was a smash hit." },
    { "word": "So far so good", "pronounce": "so far so gud", "def": "Sejauh ini baik-baik saja", "ex": "So far so good." },
    { "word": "Sour grapes", "pronounce": "sau-er greips", "def": "Meremehkan sesuatu yang tak bisa diraih", "ex": "He said it was sour grapes." },
    { "word": "Steal someone's thunder", "pronounce": "stil sam-wans than-der", "def": "Mencuri perhatian orang lain", "ex": "Don't steal my thunder." },
    { "word": "Stick out like a sore thumb", "pronounce": "stik aut laik a sor tham", "def": "Sangat mencolok", "ex": "He sticks out like a sore thumb." }
  ]
},{
  "name": "Idiom 3",
  "items": [
    { "word": "Smell a rat", "pronounce": "smel a rat", "def": "Mencurigai", "ex": "I smell a rat in this deal." },
    { "word": "Speak of the devil", "pronounce": "spik of the de-vil", "def": "Baru saja dibicarakan", "ex": "Speak of the devil, here he is!" },
    { "word": "Spill the beans", "pronounce": "spil the bins", "def": "Membocorkan rahasia", "ex": "She spilled the beans." },
    { "word": "Spill the tea", "pronounce": "spil the ti", "def": "Menggosip", "ex": "Come on, spill the tea!" },
    { "word": "At a loss for words", "pronounce": "at a los for werds", "def": "Kehilangan kata-kata", "ex": "I'm at a loss for words." },
    { "word": "Keep your chin up", "pronounce": "kip yor chin ap", "def": "Tetap tegar", "ex": "Keep your chin up!" },
    { "word": "Burn the midnight oil", "pronounce": "bern the mid-nayt oil", "def": "Bekerja larut malam", "ex": "I burned the midnight oil to finish it." },
    { "word": "Stick to one's guns", "pronounce": "stik tu wans gans", "def": "Teguh pada pendirian", "ex": "She stuck to her guns." },
    { "word": "Take it easy", "pronounce": "teyk it i-zi", "def": "Santai saja", "ex": "Take it easy, man." },
    { "word": "Take the cake", "pronounce": "teyk the keyk", "def": "Paling mencolok", "ex": "That takes the cake!" },
    { "word": "Take the fall", "pronounce": "teyk the fol", "def": "Menanggung kesalahan", "ex": "He took the fall for his friend." },
    { "word": "That's the last straw", "pronounce": "dats the last stro", "def": "Kesabaran habis", "ex": "That's the last straw!" },
    { "word": "A lone wolf", "pronounce": "a lon wulf", "def": "Penyendiri", "ex": "He's a lone wolf." },
    { "word": "Back the wrong horse", "pronounce": "bak the rong hors", "def": "Membuat keputusan salah", "ex": "I backed the wrong horse." },
    { "word": "Back to square one", "pronounce": "bak tu skwer wan", "def": "Kembali ke awal", "ex": "We're back to square one." },
    { "word": "Beat around the bush", "pronounce": "bit a-raund the bush", "def": "Bertele-tele", "ex": "Stop beating around the bush." },
    { "word": "Beats me", "pronounce": "bits mi", "def": "Saya tidak tahu", "ex": "Beats me, I have no idea." },
    { "word": "Bend over backward", "pronounce": "bend o-ver bak-word", "def": "Berusaha keras", "ex": "I bent over backward to help him." },
    { "word": "Binge watch", "pronounce": "binj woch", "def": "Nonton maraton", "ex": "I binge watched the whole series." },
    { "word": "Bite off more than you can chew", "pronounce": "bait of mor than yu kan chu", "def": "Ambil tanggung jawab terlalu banyak", "ex": "Don't bite off more than you can chew." },
    { "word": "Bite the bullet", "pronounce": "bait the bu-let", "def": "Terpaksa lakukan hal sulit", "ex": "I had to bite the bullet." },
    { "word": "Bite your tongue", "pronounce": "bait yor tang", "def": "Menahan bicara", "ex": "I had to bite my tongue." },
    { "word": "Blow off steam", "pronounce": "blo of stim", "def": "Melepaskan emosi", "ex": "He went for a run to blow off steam." },
    { "word": "Break the bank", "pronounce": "breyk the bank", "def": "Menghabiskan semua uang", "ex": "That won't break the bank." },
    { "word": "By the skin of your teeth", "pronounce": "bai the skin of yor tit", "def": "Hampir saja gagal", "ex": "I passed by the skin of my teeth." },
    { "word": "Call it a day", "pronounce": "kol it a dey", "def": "Berhenti untuk hari itu", "ex": "Let's call it a day." },
    { "word": "Cat got your tongue", "pronounce": "kat got yor tang", "def": "Kenapa diam saja?", "ex": "What's wrong? Cat got your tongue?" },
    { "word": "Come hell or high water", "pronounce": "kam hel or hai wo-ter", "def": "Apapun yang terjadi", "ex": "I'll be there, come hell or high water." }
  ]
},{
  "name": "Idiom 4",
  "items": [
    { "word": "Open one's big mouth", "pronounce": "o-pen wans big maut", "def": "Keceplosan", "ex": "I opened my big mouth again." },
    { "word": "Break a leg", "pronounce": "breyk a leg", "def": "Semoga sukses", "ex": "Break a leg on your performance!" },
    { "word": "Break the ice", "pronounce": "breyk the ais", "def": "Mencairkan suasana", "ex": "I broke the ice with a joke." },
    { "word": "Brown-nose", "pronounce": "braun-nos", "def": "Mencari muka", "ex": "He's always brown-nosing the boss." },
    { "word": "Burn out", "pronounce": "bern aut", "def": "Kelelahan total", "ex": "I'm burned out from work." },
    { "word": "Burn the midnight oil", "pronounce": "bern the mid-nayt oil", "def": "Lembur", "ex": "I burned the midnight oil to finish." },
    { "word": "Burn one's bridges", "pronounce": "bern wans bri-jes", "def": "Putus hubungan baik", "ex": "Don't burn your bridges." },
    { "word": "Call it a day", "pronounce": "kol it a dey", "def": "Berhenti", "ex": "Let's call it a day." },
    { "word": "Catch some Z's", "pronounce": "kec sam zis", "def": "Tidur", "ex": "I need to catch some Z's." },
    { "word": "Out of sorts", "pronounce": "aut of sorts", "def": "Kurang sehat", "ex": "I feel out of sorts today." },
    { "word": "Caught red-handed", "pronounce": "kot red-han-ded", "def": "Tertangkap basah", "ex": "He was caught red-handed." },
    { "word": "Be on someone's case", "pronounce": "bi on sam-wans keys", "def": "Cerewet", "ex": "My boss is always on my case." },
    { "word": "Dirt cheap", "pronounce": "dert chip", "def": "Murah meriah", "ex": "This phone is dirt cheap." },
    { "word": "Bite the dust", "pronounce": "bait the dust", "def": "Gagal total", "ex": "Another project bit the dust." },
    { "word": "Get cold feet", "pronounce": "get kold fit", "def": "Gugup", "ex": "I got cold feet before the exam." },
    { "word": "Cost an arm and a leg", "pronounce": "kost an arm and a leg", "def": "Sangat mahal", "ex": "The car cost an arm and a leg." },
    { "word": "Cry over spilt milk", "pronounce": "krai o-ver spilt milk", "def": "Menyesali hal yang sudah terjadi", "ex": "Don't cry over spilt milk." },
    { "word": "Crybaby", "pronounce": "krai-bey-bi", "def": "Cengeng", "ex": "Stop being a crybaby!" },
    { "word": "Cut corners", "pronounce": "kat kor-ners", "def": "Memotong prosedur", "ex": "Don't cut corners on safety." },
    { "word": "Cut it out", "pronounce": "kat it aut", "def": "Hentikan", "ex": "Cut it out! That's annoying." },
    { "word": "Dead meat", "pronounce": "ded mit", "def": "Dalam masalah besar", "ex": "You're dead meat!" },
    { "word": "Eat humble pie", "pronounce": "it ham-bel pai", "def": "Mengakui kesalahan", "ex": "He had to eat humble pie." },
    { "word": "Smart cookie", "pronounce": "smart ku-ki", "def": "Orang pintar", "ex": "She's a smart cookie." },
    { "word": "Eye candy", "pronounce": "ai kan-di", "def": "Enak dilihat", "ex": "That car is pure eye candy." },
    { "word": "Face the music", "pronounce": "feys the myu-zik", "def": "Hadapi konsekuensi", "ex": "It's time to face the music." },
    { "word": "Feel under the weather", "pronounce": "fil an-der the we-ther", "def": "Merasa tidak enak badan", "ex": "I feel under the weather." },
    { "word": "Fever pitch", "pronounce": "fi-ver pich", "def": "Antusiasme tinggi", "ex": "Excitement is at fever pitch." },
    { "word": "Get out of hand", "pronounce": "get aut of hand", "def": "Tidak terkendali", "ex": "The party got out of hand." },
    { "word": "Give someone the cold shoulder", "pronounce": "giv sam-wan the kold shol-der", "def": "Mengabaikan seseorang", "ex": "She gave me the cold shoulder." },
    { "word": "Go the extra mile", "pronounce": "go the eks-tra mail", "def": "Berusaha lebih", "ex": "He always goes the extra mile." }
  ]
},{
  "name": "Idiom 5",
  "items": [
    { "word": "Fess up", "pronounce": "fes ap", "def": "Mengaku", "ex": "You should fess up and tell the truth." },
    { "word": "Fish out of water", "pronounce": "fish aut of wo-ter", "def": "Merasa asing", "ex": "I feel like a fish out of water here." },
    { "word": "Get cold feet", "pronounce": "get kold fit", "def": "Jadi ragu-ragu", "ex": "I got cold feet before the interview." },
    { "word": "Get one's ducks in a row", "pronounce": "get wans daks in a ro", "def": "Persiapkan dengan rapi", "ex": "I need to get my ducks in a row before the trip." },
    { "word": "Go down in flames", "pronounce": "go daun in fleymz", "def": "Gagal total", "ex": "His plan went down in flames." },
    { "word": "Go the extra mile", "pronounce": "go the eks-tra mail", "def": "Berusaha lebih", "ex": "She always goes the extra mile." },
    { "word": "God forbid", "pronounce": "god for-bid", "def": "Semoga tidak terjadi", "ex": "God forbid we run out of money." },
    { "word": "Have an attitude", "pronounce": "hav an a-ti-tud", "def": "Bersikap angkuh", "ex": "She has an attitude today." },
    { "word": "Hang in there", "pronounce": "hang in ther", "def": "Tetap semangat", "ex": "Hang in there, it'll get better." },
    { "word": "Hit the books", "pronounce": "hit the buks", "def": "Belajar keras", "ex": "I need to hit the books for my exam." },
    { "word": "Hit the ceiling", "pronounce": "hit the si-ling", "def": "Marah besar", "ex": "My boss hit the ceiling when I was late." },
    { "word": "Hit the jackpot", "pronounce": "hit the jak-pot", "def": "Berhasil besar", "ex": "We hit the jackpot with this investment." },
    { "word": "Hit the nail on the head", "pronounce": "hit the neyl on the hed", "def": "Tepat sasaran", "ex": "You hit the nail on the head." },
    { "word": "Hit the road", "pronounce": "hit the rod", "def": "Berangkat", "ex": "We should hit the road early." },
    { "word": "Hit the sack", "pronounce": "hit the sak", "def": "Pergi tidur", "ex": "I'm tired, I'm going to hit the sack." },
    { "word": "Hold your horses", "pronounce": "hold yor hor-sis", "def": "Sabar dulu", "ex": "Hold your horses, we're not ready." },
    { "word": "I'm beat", "pronounce": "aim bit", "def": "Saya lelah", "ex": "I'm beat after a long day." },
    { "word": "In a pickle", "pronounce": "in a pi-kel", "def": "Dalam masalah", "ex": "I'm in a pickle right now." },
    { "word": "In hot water", "pronounce": "in hot wo-ter", "def": "Dalam masalah", "ex": "He's in hot water with his boss." },
    { "word": "In the dark", "pronounce": "in the dark", "def": "Tidak tahu apa-apa", "ex": "I'm completely in the dark about it." },
    { "word": "In the loop", "pronounce": "in the lup", "def": "Mendapat informasi", "ex": "Keep me in the loop." },
    { "word": "It sucks", "pronounce": "it saks", "def": "Payah", "ex": "This movie sucks." },
    { "word": "It's baloney", "pronounce": "its ba-lo-ni", "def": "Itu omong kosong", "ex": "That story is baloney." },
    { "word": "It's easy peasy", "pronounce": "its i-zi pi-zi", "def": "Gampang banget", "ex": "The test was easy peasy." },
    { "word": "Jump the gun", "pronounce": "jamp the gan", "def": "Bertindak terlalu cepat", "ex": "Don't jump the gun, wait for instructions." },
    { "word": "Kick the bucket", "pronounce": "kik the ba-ket", "def": "Mati", "ex": "He's old enough to kick the bucket anytime." },
    { "word": "Let sleeping dogs lie", "pronounce": "let slip-ing dogz lai", "def": "Jangan bangkitkan masalah lama", "ex": "Let sleeping dogs lie, don't bring up that issue." },
    { "word": "Make a long story short", "pronounce": "meyk a long stor-i short", "def": "Singkat cerita", "ex": "To make a long story short, we won." }
  ]
},{
  "name": "Idiom 6",
  "items": [
    { "word": "Jump for joy", "pronounce": "jamp for joi", "def": "Melompat gembira", "ex": "She jumped for joy when she heard the news." },
    { "word": "Jump on the bandwagon", "pronounce": "jamp on the band-wa-gon", "def": "Ikut tren", "ex": "Don't just jump on the bandwagon." },
    { "word": "Jump the gun", "pronounce": "jamp the gan", "def": "Bertindak terlalu cepat", "ex": "Don't jump the gun, wait for instructions." },
    { "word": "Keep your cool", "pronounce": "kip yor kul", "def": "Tetap tenang", "ex": "She kept her cool during the argument." },
    { "word": "Let bygones be bygones", "pronounce": "let bai-gons bi bai-gons", "def": "Lupakan masa lalu", "ex": "We should let bygones be bygones." },
    { "word": "Let it slide", "pronounce": "let it slaid", "def": "Biarkan berlalu", "ex": "I'll let it slide this time." },
    { "word": "Let the cat out of the bag", "pronounce": "let the kat aut of the bag", "def": "Membocorkan rahasia", "ex": "He let the cat out of the bag." },
    { "word": "Take a load off", "pronounce": "teyk a lod of", "def": "Bersantai", "ex": "Take a load off and relax." },
    { "word": "Make up your mind", "pronounce": "meyk ap yor maind", "def": "Ambil keputusan", "ex": "You need to make up your mind." },
    { "word": "Miss the boat", "pronounce": "mis the bot", "def": "Kehilangan kesempatan", "ex": "Don't miss the boat, apply now." },
    { "word": "Throw in the towel", "pronounce": "thro in the ta-wel", "def": "Menyerah", "ex": "I'm not ready to throw in the towel." },
    { "word": "Throw shade", "pronounce": "thro sheyd", "def": "Menyindir halus", "ex": "She likes to throw shade at her rivals." },
    { "word": "Tie the knot", "pronounce": "tai the not", "def": "Menikah", "ex": "They tied the knot last year." },
    { "word": "Make a pass at", "pronounce": "meyk a pas at", "def": "Menggoda", "ex": "He made a pass at her at the party." },
    { "word": "Go bananas", "pronounce": "go ba-na-nas", "def": "Menjadi gila", "ex": "The crowd went bananas when the band started." },
    { "word": "Turn a blind eye", "pronounce": "tern a blaind ai", "def": "Pura-pura tidak tahu", "ex": "They turned a blind eye to the problem." },
    { "word": "Under the weather", "pronounce": "an-der the we-ther", "def": "Tidak enak badan", "ex": "I'm feeling under the weather today." },
    { "word": "Under your nose", "pronounce": "an-der yor nos", "def": "Tepat di depan mata", "ex": "It was right under your nose the whole time." },
    { "word": "Up in the air", "pronounce": "ap in the er", "def": "Masih belum pasti", "ex": "The plans are still up in the air." },
    { "word": "When pigs fly", "pronounce": "wen pigz flai", "def": "Mustahil terjadi", "ex": "He'll finish it when pigs fly." },
    { "word": "Zip your lip", "pronounce": "zip yor lip", "def": "Tutup mulut", "ex": "Zip your lip and listen to me." }
  ]
},{
  "name": "Idiom 7",
  "items": [
    { "word": "Up in arms", "pronounce": "ap in arms", "def": "Marah besar", "ex": "The residents are up in arms about the new policy." },
    { "word": "Up to speed", "pronounce": "ap tu spid", "def": "Tahu perkembangan terbaru", "ex": "I need to get up to speed on this project." },
    { "word": "Walk on air", "pronounce": "wok on er", "def": "Sangat bahagia", "ex": "She was walking on air after getting the promotion." },
    { "word": "Watch your step", "pronounce": "woch yor step", "def": "Hati-hati", "ex": "Watch your step, the floor is slippery." },
    { "word": "Window shopping", "pronounce": "win-do shop-ing", "def": "Cuci mata", "ex": "We were just window shopping." },
    { "word": "At the drop of a hat", "pronounce": "at the drop of a hat", "def": "Tanpa ragu", "ex": "He would help me at the drop of a hat." },
    { "word": "Bark is worse than bite", "pronounce": "bark iz wers than bait", "def": "Gonggongannya lebih keras daripada gigitannya", "ex": "Don't worry, his bark is worse than his bite." },
    { "word": "Beat the clock", "pronounce": "bit the klok", "def": "Selesai tepat waktu", "ex": "We beat the clock and finished early." },
    { "word": "Better late than never", "pronounce": "be-ter leyt than ne-ver", "def": "Lebih lambat daripada tidak sama sekali", "ex": "Better late than never, I finally did it." },
    { "word": "Call it a night", "pronounce": "kol it a nait", "def": "Berhenti malam itu juga", "ex": "Let's call it a night." },
    { "word": "Cut to the chase", "pronounce": "kat tu the cheys", "def": "Langsung ke inti", "ex": "Let's cut to the chase, what's the problem?" },
    { "word": "Don't count your chickens before they hatch", "pronounce": "dont kaunt yor chi-kenz bi-for they hach", "def": "Jangan berharap sebelum waktunya", "ex": "Don't count your chickens before they hatch." },
    { "word": "Elbow grease", "pronounce": "el-bo gris", "def": "Kerja keras fisik", "ex": "It took a lot of elbow grease to clean this." },
    { "word": "Every cloud has a silver lining", "pronounce": "ev-ri klaud haz a sil-ver lai-ning", "def": "Selalu ada hikmah di balik musibah", "ex": "Every cloud has a silver lining." },
    { "word": "Fit as a fiddle", "pronounce": "fit as a fi-dl", "def": "Sehat dan bugar", "ex": "My grandfather is fit as a fiddle." },
    { "word": "Get a kick out of something", "pronounce": "get a kik aut of sam-thing", "def": "Sangat menikmati sesuatu", "ex": "I get a kick out of watching old movies." },
    { "word": "Go back to the drawing board", "pronounce": "go bak tu the dro-ing bord", "def": "Mulai lagi dari awal", "ex": "The plan failed, so go back to the drawing board." },
    { "word": "Have a sweet tooth", "pronounce": "hav a swit tuth", "def": "Suka makanan manis", "ex": "I have a sweet tooth." },
    { "word": "Hit the hay", "pronounce": "hit the hey", "def": "Pergi tidur", "ex": "It's late, I'm going to hit the hay." },
    { "word": "It takes two to tango", "pronounce": "it teyks tu tu tang-go", "def": "Masalah tidak hanya dari satu pihak", "ex": "It takes two to tango, they both are responsible." },
    { "word": "Keep an eye on", "pronounce": "kip an ai on", "def": "Mengawasi", "ex": "Could you keep an eye on my bag?" },
    { "word": "Let off steam", "pronounce": "let of stim", "def": "Melepaskan emosi", "ex": "He went for a run to let off steam." }
  ]
},{
  "name": "Idiom 8",
  "items": [
    { "word": "Hear it on the grapevine", "pronounce": "hir it on the greyp-vain", "def": "Mendengar kabar desas-desus", "ex": "I heard it on the grapevine that she got promoted." },
    { "word": "Hit the hay", "pronounce": "hit the hey", "def": "Pergi tidur", "ex": "I'm exhausted, I'm going to hit the hay." },
    { "word": "It takes two to tango", "pronounce": "it teyks tu tu tang-go", "def": "Masalah tidak hanya dari satu pihak", "ex": "They both argued, but it takes two to tango." },
    { "word": "Keep an eye on him", "pronounce": "kip an ai on him", "def": "Awasi dia", "ex": "Keep an eye on him while I'm gone." },
    { "word": "Let sleeping dogs lie", "pronounce": "let slip-ing dogz lai", "def": "Jangan bangkitkan masalah lama", "ex": "Let sleeping dogs lie, don't bring up the past." },
    { "word": "Make a long story short", "pronounce": "meyk a long stor-i short", "def": "Singkat cerita", "ex": "To make a long story short, we won the game." },
    { "word": "On the rocks", "pronounce": "on the roks", "def": "Sedang bermasalah", "ex": "Their marriage is on the rocks." },
    { "word": "Once in a blue moon", "pronounce": "wans in a blu mun", "def": "Sangat jarang", "ex": "He visits once in a blue moon." },
    { "word": "Play devil's advocate", "pronounce": "pley de-vil's ad-vo-kat", "def": "Berdebat untuk sisi sebaliknya", "ex": "I'm just playing devil's advocate here." },
    { "word": "Put your foot in your mouth", "pronounce": "put yor fut in yor maut", "def": "Bicara yang menyinggung", "ex": "I put my foot in my mouth with that comment." },
    { "word": "Ring a bell", "pronounce": "ring a bel", "def": "Terdengar familiar", "ex": "That name rings a bell." },
    { "word": "Sit on the fence", "pronounce": "sit on the fens", "def": "Tidak memihak", "ex": "You can't sit on the fence forever." },
    { "word": "Steal someone's thunder", "pronounce": "stil sam-wans than-der", "def": "Mencuri perhatian", "ex": "Don't steal my thunder." },
    { "word": "Straight from the horse's mouth", "pronounce": "streyt from the hor-sis maut", "def": "Langsung dari sumber terpercaya", "ex": "I heard it straight from the horse's mouth." },
    { "word": "The ball is in your court", "pronounce": "the bol iz in yor kort", "def": "Giliranmu yang bertindak", "ex": "I've done my part, now the ball is in your court." },
    { "word": "The pot calling the kettle black", "pronounce": "the pot kol-ing the ke-tl blak", "def": "Orang salah menyalahkan orang lain", "ex": "It's the pot calling the kettle black, you did the same thing." },
    { "word": "Through thick and thin", "pronounce": "thru thik and thin", "def": "Dalam suka dan duka", "ex": "He's been with me through thick and thin." },
    { "word": "Time flies when you're having fun", "pronounce": "taim flaiz wen yor hav-ing fan", "def": "Waktu berlalu cepat saat bersenang-senang", "ex": "Time flies when you're having fun." },
    { "word": "Twist someone's arm", "pronounce": "twist sam-wans arm", "def": "Memaksa seseorang", "ex": "I had to twist his arm to get him to come." },
    { "word": "Up in the air", "pronounce": "ap in the er", "def": "Masih belum pasti", "ex": "The decision is still up in the air." },
    { "word": "Wear your heart on your sleeve", "pronounce": "wer yor hart on yor sliv", "def": "Mudah menunjukkan perasaan", "ex": "She always wears her heart on her sleeve." },
    { "word": "When pigs fly", "pronounce": "wen pigz flai", "def": "Mustahil terjadi", "ex": "He'll do it when pigs fly." },
    { "word": "You can say that again", "pronounce": "yu kan sey that a-gen", "def": "Setuju banget", "ex": "You can say that again, I completely agree." },
    { "word": "Zip your lip", "pronounce": "zip yor lip", "def": "Tutup mulut", "ex": "Zip your lip and pay attention." },
    { "word": "A snowball effect", "pronounce": "a sno-bol e-fekt", "def": "Efek bola salju", "ex": "The problem had a snowball effect." },
    { "word": "Blow a fuse", "pronounce": "blo a fyuz", "def": "Tiba-tiba marah besar", "ex": "He blew a fuse when he saw the bill." },
    { "word": "Champ at the bit", "pronounce": "champ at the bit", "def": "Tidak sabar untuk memulai", "ex": "She's champing at the bit to start her new job." },
    { "word": "Drive someone up the wall", "pronounce": "draiv sam-wan ap the wol", "def": "Membuat seseorang kesal sekali", "ex": "That noise is driving me up the wall." },
    { "word": "Get your act together", "pronounce": "get yor ak t-ge-ther", "def": "Berbenah", "ex": "You need to get your act together." }
  ]
}
];