var phrasesData = [
  {
  "name": "Alam",
  "items": [
    { "word": "Die out", "pronounce": "dai aut", "def": "Punah", "ex": "Many species will die out if we don't protect them." },
    { "word": "Dry up", "pronounce": "drai ap", "def": "Mengering", "ex": "The river dried up during the drought." },
    { "word": "Warm up", "pronounce": "worm ap", "def": "Menghangat", "ex": "The Earth is warming up due to climate change." },
    { "word": "Blow away", "pronounce": "blo a-wey", "def": "Tertiup angin", "ex": "The leaves blew away in the storm." },
    { "word": "Blow up", "pronounce": "blo ap", "def": "Meledak", "ex": "The volcano blew up with a huge explosion." },
    { "word": "Clear up", "pronounce": "kliar ap", "def": "Cerah", "ex": "The sky cleared up after the rain." },
    { "word": "Cool down", "pronounce": "kul daun", "def": "Menjadi dingin", "ex": "The temperature will cool down at night." },
    { "word": "Flood out", "pronounce": "flad aut", "def": "Terendam banjir", "ex": "The village was flooded out by the heavy rain." },
    { "word": "Give off", "pronounce": "giv of", "def": "Mengeluarkan bau/asap", "ex": "The factory gives off toxic fumes." },
    { "word": "Fall", "pronounce": "fol", "def": "Turun hujan/salju", "ex": "Snow will fall tonight." },
    { "word": "Grow over", "pronounce": "gro o-ver", "def": "Menumbuhi", "ex": "Weeds grew over the abandoned garden." },
    { "word": "Wear away", "pronounce": "wer a-wey", "def": "Mengikis", "ex": "The river wears away the rocks over time." },
    { "word": "Run out", "pronounce": "ran aut", "def": "Habis", "ex": "Our water supply will run out soon." },
    { "word": "Melt away", "pronounce": "melt a-wey", "def": "Mencair", "ex": "The snow melted away in the spring sun." },
    { "word": "Radiate out", "pronounce": "rey-di-eyt aut", "def": "Memancar", "ex": "Heat radiates out from the sun." },
    { "word": "Sublimate into", "pronounce": "sab-li-meyt in-tu", "def": "Menyublim", "ex": "The ice sublimated into water vapor." },
    { "word": "Evaporate into", "pronounce": "i-va-po-reyt in-tu", "def": "Menguap", "ex": "Water evaporates into the air." },
    { "word": "Settle", "pronounce": "se-tel", "def": "Mengendap", "ex": "Sediment settles at the bottom of the river." },
    { "word": "Pollute with", "pronounce": "po-lut with", "def": "Mencemari", "ex": "The factory pollutes the river with chemicals." },
    { "word": "Recycle into", "pronounce": "ri-sai-kel in-tu", "def": "Mendaur ulang", "ex": "Plastic can be recycled into new products." },
    { "word": "Soak up", "pronounce": "sok ap", "def": "Menyerap", "ex": "Trees soak up carbon dioxide." },
    { "word": "Flow out", "pronounce": "flo aut", "def": "Mengalir", "ex": "The river flows out to the sea." },
    { "word": "Flood", "pronounce": "flad", "def": "Membanjiri", "ex": "The heavy rain will flood the area." },
    { "word": "Spill over", "pronounce": "spil o-ver", "def": "Meluap", "ex": "The river spilled over its banks." },
    { "word": "Withstand", "pronounce": "with-stand", "def": "Bertahan", "ex": "The tree can withstand strong winds." }
  ]
},{
  "name": "Uang",
  "items": [
    { "word": "Save up", "pronounce": "seiv ap", "def": "Menabung", "ex": "I want to save up for a new phone." },
    { "word": "Run out of", "pronounce": "ran aut of", "def": "Kehabisan", "ex": "We ran out of milk." },
    { "word": "Pay for", "pronounce": "pey for", "def": "Membayar untuk", "ex": "I will pay for dinner." },
    { "word": "Splash out on", "pronounce": "splash aut on", "def": "Menghamburkan uang", "ex": "She splashed out on a new dress." },
    { "word": "Cut back on", "pronounce": "kat bak on", "def": "Mengurangi pengeluaran", "ex": "I need to cut back on spending." },
    { "word": "Fork out", "pronounce": "fork aut", "def": "Mengeluarkan uang dengan enggan", "ex": "I had to fork out $100 for the repair." },
    { "word": "Shop around", "pronounce": "shop a-raund", "def": "Membandingkan harga", "ex": "You should shop around for the best price." },
    { "word": "Buy", "pronounce": "bai", "def": "Membeli", "ex": "I want to buy a new book." },
    { "word": "Sell out", "pronounce": "sel aut", "def": "Habis terjual", "ex": "The tickets sold out quickly." },
    { "word": "Mark down", "pronounce": "mark daun", "def": "Menurunkan harga", "ex": "The store marked down the prices." },
    { "word": "Run out of money", "pronounce": "ran aut of ma-ni", "def": "Habis uang", "ex": "I ran out of money." },
    { "word": "Run up", "pronounce": "ran ap", "def": "Berhutang", "ex": "He ran up a big debt." },
    { "word": "Pay back", "pronounce": "pey bak", "def": "Membayar kembali", "ex": "I need to pay back the loan." },
    { "word": "Set aside", "pronounce": "set a-said", "def": "Menyisihkan uang", "ex": "She sets aside money each month." },
    { "word": "Swap out", "pronounce": "swap aut", "def": "Menukar barang", "ex": "You can swap out the item for a new one." },
    { "word": "Cross off", "pronounce": "kros of", "def": "Mencoret (tidak jadi beli)", "ex": "I crossed off that item from my list." },
    { "word": "Get off", "pronounce": "get of", "def": "Mendapat diskon", "ex": "I got 20% off the price." },
    { "word": "Stock up on", "pronounce": "stok ap on", "def": "Membeli banyak", "ex": "We stocked up on food for the winter." },
    { "word": "Haggle over", "pronounce": "ha-gel o-ver", "def": "Menawar harga", "ex": "She haggled over the price of the bag." },
    { "word": "Charge to", "pronounce": "charj tu", "def": "Membeli dengan kredit", "ex": "I charged the purchase to my card." },
    { "word": "Shell out", "pronounce": "shel aut", "def": "Membelanjakan", "ex": "I had to shell out $50 for the ticket." },
    { "word": "Put aside for", "pronounce": "put a-said for", "def": "Menabung untuk", "ex": "She put aside money for a rainy day." },
    { "word": "Take back", "pronounce": "teyk bak", "def": "Mengembalikan barang", "ex": "I took the shirt back to the store." },
    { "word": "Lend out", "pronounce": "lend aut", "def": "Meminjamkan", "ex": "He lends out his books to friends." },
    { "word": "Count out", "pronounce": "kaunt aut", "def": "Menghitung ulang", "ex": "She counted out the money carefully." }
  ]
},{
  "name": "Emosi",
  "items": [
    { "word": "Cheer up", "pronounce": "chir ap", "def": "Menghibur", "ex": "I tried to cheer her up." },
    { "word": "Fall for", "pronounce": "fol for", "def": "Jatuh cinta", "ex": "She fell for him instantly." },
    { "word": "Break up", "pronounce": "breyk ap", "def": "Putus hubungan", "ex": "They decided to break up." },
    { "word": "Get along with", "pronounce": "get a-long with", "def": "Rukun", "ex": "I get along with my colleagues." },
    { "word": "Fall out with", "pronounce": "fol aut with", "def": "Bertengkar dengan", "ex": "She fell out with her best friend." },
    { "word": "Make up", "pronounce": "meyk ap", "def": "Berdamai", "ex": "They made up after the argument." },
    { "word": "Let down", "pronounce": "let daun", "def": "Mengecewakan", "ex": "I felt let down by his promise." },
    { "word": "Hold back", "pronounce": "hold bak", "def": "Menahan emosi", "ex": "She held back her tears." },
    { "word": "Open up", "pronounce": "o-pen ap", "def": "Membuka diri", "ex": "He opened up about his feelings." },
    { "word": "Stick up for", "pronounce": "stik ap for", "def": "Membela", "ex": "She stuck up for her friend." },
    { "word": "Calm down", "pronounce": "kam daun", "def": "Menenangkan", "ex": "Please calm down and explain." },
    { "word": "Break down", "pronounce": "breyk daun", "def": "Menangis", "ex": "He broke down in tears." },
    { "word": "Bottle up", "pronounce": "bo-tel ap", "def": "Memendam perasaan", "ex": "Don't bottle up your emotions." },
    { "word": "Pour out", "pronounce": "por aut", "def": "Meluapkan", "ex": "She poured out her heart to me." },
    { "word": "Let out", "pronounce": "let aut", "def": "Mencurahkan", "ex": "He let out his frustration." },
    { "word": "Rein in", "pronounce": "reyn in", "def": "Mengendalikan", "ex": "You need to rein in your anger." },
    { "word": "Feel guilty", "pronounce": "fil gil-ti", "def": "Merasa bersalah", "ex": "I feel guilty about what happened." },
    { "word": "Forgive for", "pronounce": "for-giv for", "def": "Memaafkan", "ex": "She forgave him for his mistake." },
    { "word": "Take out on", "pronounce": "teyk aut on", "def": "Melampiaskan", "ex": "Don't take your anger out on me." },
    { "word": "Relate to", "pronounce": "ri-leyt tu", "def": "Berempati", "ex": "I can relate to your situation." },
    { "word": "Worry about", "pronounce": "wa-ri a-baut", "def": "Mengkhawatirkan", "ex": "Don't worry about me." },
    { "word": "Celebrate with", "pronounce": "se-le-breyt with", "def": "Merayakan", "ex": "We celebrate with our friends." },
    { "word": "Shut out", "pronounce": "shat aut", "def": "Mengabaikan", "ex": "She shut him out of her life." }
  ]
},{
  "name": "Percakapan",
  "items": [
    { "word": "Give up", "pronounce": "giv ap", "def": "Menyerah", "ex": "Don't give up on your dreams." },
    { "word": "Break down", "pronounce": "breyk daun", "def": "Rusak", "ex": "My car broke down on the highway." },
    { "word": "Show up", "pronounce": "sho ap", "def": "Muncul", "ex": "He didn't show up to the party." },
    { "word": "Run out of", "pronounce": "ran aut of", "def": "Kehabisan", "ex": "We ran out of sugar." },
    { "word": "Figure out", "pronounce": "fig-yer aut", "def": "Memahami", "ex": "I can't figure out this problem." },
    { "word": "Bring up", "pronounce": "bring ap", "def": "Mengangkat topik", "ex": "She brought up an interesting topic." },
    { "word": "Look after", "pronounce": "luk af-ter", "def": "Mengurus", "ex": "Please look after my cat." },
    { "word": "Find out", "pronounce": "faind aut", "def": "Menemukan", "ex": "We need to find out the truth." },
    { "word": "Hang on", "pronounce": "hang on", "def": "Bersabar", "ex": "Hang on, I'll be right back." },
    { "word": "Come back", "pronounce": "kam bak", "def": "Kembali", "ex": "Please come back soon." },
    { "word": "Go away", "pronounce": "go a-wey", "def": "Pergi", "ex": "The pain won't go away." },
    { "word": "Try out", "pronounce": "trai aut", "def": "Mencoba", "ex": "I want to try out this new recipe." },
    { "word": "Put off", "pronounce": "put of", "def": "Menunda", "ex": "Don't put off your homework." },
    { "word": "Call off", "pronounce": "kol of", "def": "Membatalkan", "ex": "They called off the meeting." },
    { "word": "Write down", "pronounce": "rait daun", "def": "Menulis", "ex": "Please write down your name." },
    { "word": "Read out", "pronounce": "rid aut", "def": "Membaca", "ex": "She read out the instructions." },
    { "word": "Finish up", "pronounce": "fi-nish ap", "def": "Menyelesaikan", "ex": "Let's finish up this project." },
    { "word": "Start", "pronounce": "start", "def": "Memulai", "ex": "We should start the meeting." },
    { "word": "Think over", "pronounce": "think o-ver", "def": "Berpikir", "ex": "I need to think over your offer." },
    { "word": "Help out", "pronounce": "help aut", "def": "Membantu", "ex": "Can you help out with this?" },
    { "word": "Get together", "pronounce": "get to-ge-ther", "def": "Berkumpul", "ex": "Let's get together this weekend." }
  ]
},{
  "name": "Karier",
  "items": [
    { "word": "Move up", "pronounce": "muv ap", "def": "Naik jabatan", "ex": "He wants to move up in his company." },
    { "word": "Break into", "pronounce": "breyk in-tu", "def": "Masuk ke bidang baru", "ex": "She broke into the tech industry." },
    { "word": "Step down", "pronounce": "step daun", "def": "Mengundurkan diri", "ex": "The CEO stepped down." },
    { "word": "Carry on", "pronounce": "ka-ri on", "def": "Melanjutkan", "ex": "We must carry on with the project." },
    { "word": "Pull off", "pronounce": "pul of", "def": "Berhasil melakukan", "ex": "She pulled off a difficult deal." },
    { "word": "Back out", "pronounce": "bak aut", "def": "Mundur dari rencana", "ex": "He backed out at the last minute." },
    { "word": "Go for", "pronounce": "go for", "def": "Mencoba meraih", "ex": "I'll go for the promotion." },
    { "word": "Live up to", "pronounce": "liv ap tu", "def": "Sesuai harapan", "ex": "He lives up to expectations." },
    { "word": "Work towards", "pronounce": "werk to-ords", "def": "Berusaha menuju", "ex": "I work towards my goals." },
    { "word": "Stick to", "pronounce": "stik tu", "def": "Berpegang pada", "ex": "Stick to your plan." },
    { "word": "Stand out", "pronounce": "stand aut", "def": "Menonjol", "ex": "She stands out at work." },
    { "word": "Climb up", "pronounce": "klim ap", "def": "Mendapatkan promosi", "ex": "He climbed up the corporate ladder." },
    { "word": "Step into", "pronounce": "step in-tu", "def": "Mengambil peran", "ex": "She stepped into a leadership role." },
    { "word": "Get over", "pronounce": "get o-ver", "def": "Mengatasi rintangan", "ex": "He got over the obstacle." },
    { "word": "Bounce back", "pronounce": "bauns bak", "def": "Bangkit kembali", "ex": "He bounced back after failure." },
    { "word": "Meet", "pronounce": "mit", "def": "Mencapai target", "ex": "We met the target." },
    { "word": "Start out", "pronounce": "start aut", "def": "Memulai karier", "ex": "I started out as an intern." },
    { "word": "Take time off", "pronounce": "teyk taim of", "def": "Berhenti sementara", "ex": "I'm taking time off next week." },
    { "word": "Get through", "pronounce": "get thru", "def": "Berhasil melewati", "ex": "We got through the tough times." },
    { "word": "Adapt to", "pronounce": "a-dap-tu", "def": "Menyesuaikan diri", "ex": "She adapted to the new environment." },
    { "word": "Network with", "pronounce": "net-werk with", "def": "Memperluas jaringan", "ex": "I network with professionals." },
    { "word": "Develop oneself", "pronounce": "di-ve-lop wan-self", "def": "Mengembangkan diri", "ex": "I want to develop myself." },
    { "word": "Walk away from", "pronounce": "wok a-wey from", "def": "Meninggalkan pekerjaan", "ex": "He walked away from his job." },
    { "word": "Take over", "pronounce": "teyk o-ver", "def": "Mengambil alih", "ex": "She will take over the project." },
    { "word": "Commit to", "pronounce": "ko-mit tu", "def": "Berkomitmen", "ex": "I commit to my work." }
  ]
},{
  "name": "Harian",
  "items": [
    { "word": "Wake up", "pronounce": "weyk ap", "def": "Bangun tidur", "ex": "I wake up at six every morning." },
    { "word": "Get up", "pronounce": "get ap", "def": "Bangun dari tempat tidur", "ex": "I got up late today." },
    { "word": "Put on", "pronounce": "put on", "def": "Memakai", "ex": "She puts on her jacket." },
    { "word": "Take off", "pronounce": "teyk of", "def": "Melepaskan", "ex": "He took off his shoes." },
    { "word": "Go out", "pronounce": "go aut", "def": "Pergi keluar", "ex": "Let's go out tonight." },
    { "word": "Sit down", "pronounce": "sit daun", "def": "Duduk", "ex": "Please sit down." },
    { "word": "Stand up", "pronounce": "stand ap", "def": "Berdiri", "ex": "Please stand up." },
    { "word": "Eat out", "pronounce": "it aut", "def": "Makan di luar", "ex": "We eat out on Friday." },
    { "word": "Turn off", "pronounce": "tern of", "def": "Mematikan", "ex": "Turn off the lights." },
    { "word": "Turn on", "pronounce": "tern on", "def": "Menyalakan", "ex": "Turn on the TV." },
    { "word": "Come in", "pronounce": "kam in", "def": "Masuk", "ex": "Please come in." },
    { "word": "Go back", "pronounce": "go bak", "def": "Kembali", "ex": "I need to go back home." },
    { "word": "Hurry up", "pronounce": "ha-ri ap", "def": "Cepat", "ex": "Hurry up, we're late!" },
    { "word": "Slow down", "pronounce": "slo daun", "def": "Pelan-pelan", "ex": "You need to slow down." },
    { "word": "Calm down", "pronounce": "kam daun", "def": "Tenang", "ex": "Calm down, everything is fine." },
    { "word": "Clean up", "pronounce": "klin ap", "def": "Membersihkan", "ex": "Please clean up your room." },
    { "word": "Pick up", "pronounce": "pik ap", "def": "Mengambil", "ex": "I'll pick up the book later." },
    { "word": "Drop off", "pronounce": "drop of", "def": "Menurunkan", "ex": "I dropped off the package." },
    { "word": "Look for", "pronounce": "luk for", "def": "Mencari", "ex": "I'm looking for my keys." },
    { "word": "Wait for", "pronounce": "weyt for", "def": "Menunggu", "ex": "Please wait for me." },
    { "word": "Hang up", "pronounce": "hang ap", "def": "Menutup telepon", "ex": "She hung up the phone." },
    { "word": "Charge up", "pronounce": "charj ap", "def": "Mengisi daya", "ex": "I need to charge up my phone." },
    { "word": "Warm up", "pronounce": "worm ap", "def": "Memanaskan", "ex": "I warm up my food in the microwave." }
  ]
},{
  "name": "Kesehatan",
  "items": [
    { "word": "Work out", "pronounce": "werk aut", "def": "Berolahraga", "ex": "I work out every morning." },
    { "word": "Warm up", "pronounce": "worm ap", "def": "Pemanasan", "ex": "Always warm up before exercising." },
    { "word": "Cool down", "pronounce": "kul daun", "def": "Pendinginan", "ex": "Don't forget to cool down after running." },
    { "word": "Come down with", "pronounce": "kam daun with", "def": "Terkena penyakit", "ex": "She came down with a cold." },
    { "word": "Throw up", "pronounce": "thro ap", "def": "Muntah", "ex": "The food made him throw up." },
    { "word": "Pass out", "pronounce": "pas aut", "def": "Pingsan", "ex": "He passed out from dehydration." },
    { "word": "Get over", "pronounce": "get o-ver", "def": "Sembuh", "ex": "She is getting over the flu." },
    { "word": "Cut down on", "pronounce": "kat daun on", "def": "Mengurangi konsumsi", "ex": "I need to cut down on sugar." },
    { "word": "Bulk up", "pronounce": "balk ap", "def": "Membesarkan otot", "ex": "He wants to bulk up for the competition." },
    { "word": "Check up", "pronounce": "cek ap", "def": "Pemeriksaan rutin", "ex": "I go for a check up every year." },
    { "word": "Get injured", "pronounce": "get in-jurd", "def": "Cedera", "ex": "He got injured during the match." },
    { "word": "Recover from", "pronounce": "ri-ka-ver from", "def": "Pulih", "ex": "She recovered from her injury quickly." },
    { "word": "Break a sweat", "pronounce": "breyk a swet", "def": "Berkeringat", "ex": "I broke a sweat after 10 minutes." },
    { "word": "Lift weights", "pronounce": "lift weyts", "def": "Mengangkat beban", "ex": "He lifts weights at the gym." },
    { "word": "Stretch out", "pronounce": "strech aut", "def": "Peregangan", "ex": "I stretch out before exercising." },
    { "word": "Wash hands", "pronounce": "wosh hands", "def": "Mencuci tangan", "ex": "Wash your hands before eating." },
    { "word": "Take medicine", "pronounce": "teyk med-i-sin", "def": "Minum obat", "ex": "Don't forget to take your medicine." },
    { "word": "Rest up", "pronounce": "rest ap", "def": "Beristirahat", "ex": "You need to rest up before the exam." },
    { "word": "Get checked", "pronounce": "get chekt", "def": "Memeriksakan diri", "ex": "You should get checked by a doctor." },
    { "word": "Get vaccinated", "pronounce": "get vak-si-ney-tid", "def": "Vaksinasi", "ex": "I got vaccinated against the flu." },
    { "word": "Go on a diet", "pronounce": "go on a dai-et", "def": "Diet", "ex": "She went on a diet to lose weight." },
    { "word": "Gain weight", "pronounce": "geyn weyt", "def": "Menambah berat badan", "ex": "He gained weight during the holidays." },
    { "word": "Lose weight", "pronounce": "luz weyt", "def": "Menurunkan berat badan", "ex": "I want to lose weight this year." },
    { "word": "Go jogging", "pronounce": "go jog-ing", "def": "Lari pagi", "ex": "I go jogging every morning." },
    { "word": "Do cardio", "pronounce": "du kar-di-o", "def": "Latihan kardio", "ex": "I do cardio three times a week." }
  ]
},{
  "name": "Komunikasi",
  "items": [
    { "word": "Bring up", "pronounce": "bring ap", "def": "Mengangkat topik", "ex": "She brought up an interesting topic." },
    { "word": "Speak up", "pronounce": "spik ap", "def": "Berbicara lebih keras", "ex": "Please speak up, I can't hear you." },
    { "word": "Talk over", "pronounce": "tok o-ver", "def": "Membicarakan", "ex": "Let's talk over the details tomorrow." },
    { "word": "Cut off", "pronounce": "kat of", "def": "Memutus sambungan", "ex": "The operator cut off our call." },
    { "word": "Get through", "pronounce": "get thru", "def": "Berhasil tersambung", "ex": "I finally got through to customer service." },
    { "word": "Call back", "pronounce": "kol bak", "def": "Menelepon kembali", "ex": "I'll call you back in five minutes." },
    { "word": "Shout", "pronounce": "shaut", "def": "Berteriak", "ex": "Don't shout, I'm right here." },
    { "word": "Put through", "pronounce": "put thru", "def": "Menyambungkan telepon", "ex": "Please put me through to the manager." },
    { "word": "Speak out", "pronounce": "spik aut", "def": "Menyatakan pendapat", "ex": "She spoke out against the decision." },
    { "word": "Strike up a conversation", "pronounce": "straik ap a kon-ver-sey-shen", "def": "Mengajak ngobrol", "ex": "He struck up a conversation with his neighbor." },
    { "word": "Write back", "pronounce": "rait bak", "def": "Membalas", "ex": "I'll write back to her email tonight." },
    { "word": "Go over", "pronounce": "go o-ver", "def": "Menjelaskan", "ex": "Let me go over the instructions again." },
    { "word": "Get across", "pronounce": "get a-kros", "def": "Menyampaikan", "ex": "He got his point across clearly." },
    { "word": "Respond", "pronounce": "ri-spond", "def": "Menanggapi", "ex": "She responded to my question quickly." },
    { "word": "Shoot the breeze", "pronounce": "shut the briz", "def": "Mengobrol santai", "ex": "We were just shooting the breeze at the café." },
    { "word": "Butt in", "pronounce": "bat in", "def": "Menginterupsi", "ex": "Don't butt in when others are talking." },
    { "word": "Listen", "pronounce": "li-sen", "def": "Mendengarkan", "ex": "Please listen to what I'm saying." },
    { "word": "Repeat", "pronounce": "ri-pit", "def": "Mengulang", "ex": "Could you repeat that, please?" },
    { "word": "Clarify", "pronounce": "kla-ri-fai", "def": "Memperjelas", "ex": "Can you clarify what you mean?" },
    { "word": "Fill in", "pronounce": "fil in", "def": "Menginformasikan", "ex": "I'll fill you in on the details later." },
    { "word": "Ring up", "pronounce": "ring ap", "def": "Menelepon", "ex": "I'll ring up the office in the morning." },
    { "word": "Reach out to", "pronounce": "rich aut tu", "def": "Menghubungi", "ex": "I need to reach out to my old colleague." },
    { "word": "Text back", "pronounce": "tekst bak", "def": "Membalas pesan", "ex": "She texted back immediately." },
    { "word": "Send a message", "pronounce": "send a me-sij", "def": "Mengirim pesan", "ex": "I'll send a message to the team." },
    { "word": "Broadcast", "pronounce": "brod-kast", "def": "Menyiarkan", "ex": "The news will broadcast the event live." }
  ]
},{
  "name": "Kriminalitas",
  "items": [
    { "word": "Break in", "pronounce": "breyk in", "def": "Menerobos masuk ilegal", "ex": "Thieves broke in through the back door." },
    { "word": "Get away with", "pronounce": "get a-wey with", "def": "Lolos dari hukuman", "ex": "He thought he could get away with the crime." },
    { "word": "Turn oneself in", "pronounce": "tern wan-self in", "def": "Menyerahkan diri", "ex": "The suspect turned himself in to the police." },
    { "word": "Lock up", "pronounce": "lok ap", "def": "Mengurung di penjara", "ex": "The judge locked him up for ten years." },
    { "word": "Hold up", "pronounce": "hold ap", "def": "Merampok dengan ancaman", "ex": "Two men held up the bank." },
    { "word": "Break out", "pronounce": "breyk aut", "def": "Kabur dari penjara", "ex": "The prisoners broke out of jail." },
    { "word": "Cover up", "pronounce": "ka-ver ap", "def": "Menutupi kejahatan", "ex": "They tried to cover up the scandal." },
    { "word": "Crack down on", "pronounce": "krak daun on", "def": "Menindak tegas", "ex": "The police are cracking down on crime." },
    { "word": "Face up to", "pronounce": "feys ap tu", "def": "Menghadapi konsekuensi", "ex": "He must face up to his mistakes." },
    { "word": "Let off", "pronounce": "let of", "def": "Dibebaskan dari hukuman berat", "ex": "The judge let him off with a warning." },
    { "word": "Arrest for", "pronounce": "a-rest for", "def": "Menangkap", "ex": "He was arrested for robbery." },
    { "word": "Try for", "pronounce": "trai for", "def": "Mengadili", "ex": "He was tried for murder." },
    { "word": "Sentence to", "pronounce": "sen-tens tu", "def": "Menjatuhkan hukuman", "ex": "She was sentenced to five years." },
    { "word": "Pay a fine", "pronounce": "pey a fain", "def": "Membayar denda", "ex": "He had to pay a fine for speeding." },
    { "word": "Sue for", "pronounce": "su for", "def": "Menuntut secara hukum", "ex": "She sued the company for negligence." },
    { "word": "Fight against", "pronounce": "fait a-genst", "def": "Membantah tuduhan", "ex": "He fought against the charges." },
    { "word": "Plead guilty", "pronounce": "pled gil-ti", "def": "Mengaku bersalah", "ex": "The defendant pleaded guilty." },
    { "word": "Plead innocent", "pronounce": "pled in-o-sent", "def": "Mengaku tidak bersalah", "ex": "She pleaded innocent." },
    { "word": "Bail out", "pronounce": "beil aut", "def": "Melepaskan dengan jaminan", "ex": "His family bailed him out of jail." },
    { "word": "Question about", "pronounce": "kwes-chen a-baut", "def": "Menginterogasi", "ex": "The police questioned him about the incident." },
    { "word": "Search", "pronounce": "serch", "def": "Menggeledah rumah", "ex": "They searched the house for evidence." },
    { "word": "Confiscate from", "pronounce": "kon-fis-keyt from", "def": "Menyita barang", "ex": "The police confiscated the illegal goods." },
    { "word": "Testify against", "pronounce": "tes-ti-fai a-genst", "def": "Memberikan kesaksian", "ex": "She testified against her former boss." },
    { "word": "Bring to trial", "pronounce": "bring tu trai-al", "def": "Membawa ke pengadilan", "ex": "The case was brought to trial." },
    { "word": "Run away from", "pronounce": "ran a-wey from", "def": "Melarikan diri", "ex": "He ran away from the police." }
  ]
},{
  "name": "Solusi",
  "items": [
    { "word": "Deal with", "pronounce": "dil with", "def": "Mengatasi", "ex": "I need to deal with this problem now." },
    { "word": "Sort out", "pronounce": "sort aut", "def": "Menyelesaikan", "ex": "We need to sort out this confusion." },
    { "word": "Come up with", "pronounce": "kam ap with", "def": "Mengusulkan", "ex": "She came up with a great idea." },
    { "word": "Figure out", "pronounce": "fig-yer aut", "def": "Memahami", "ex": "I can't figure out this equation." },
    { "word": "Work out", "pronounce": "werk aut", "def": "Berhasil menyelesaikan", "ex": "Everything worked out in the end." },
    { "word": "Carry on", "pronounce": "ka-ri on", "def": "Tetap lanjut meski sulit", "ex": "We must carry on despite the challenges." },
    { "word": "Give up on", "pronounce": "giv ap on", "def": "Berhenti berharap", "ex": "Don't give up on your dreams." },
    { "word": "Back up", "pronounce": "bak ap", "def": "Mendukung", "ex": "My team backs up all my decisions." },
    { "word": "Turn to", "pronounce": "tern tu", "def": "Meminta bantuan", "ex": "I turned to my friends for support." },
    { "word": "Come down to", "pronounce": "kam daun tu", "def": "Inti masalah", "ex": "The issue comes down to money." },
    { "word": "Break down", "pronounce": "breyk daun", "def": "Mogok", "ex": "The machine broke down again." },
    { "word": "Fix up", "pronounce": "fiks ap", "def": "Memperbaiki", "ex": "We need to fix up this broken chair." },
    { "word": "Get over", "pronounce": "get o-ver", "def": "Pulih dari", "ex": "She got over the loss quickly." },
    { "word": "Get through", "pronounce": "get thru", "def": "Melewati", "ex": "We got through the tough times together." },
    { "word": "Pull through", "pronounce": "pul thru", "def": "Berhasil melewati krisis", "ex": "The patient pulled through the operation." },
    { "word": "Step in", "pronounce": "step in", "def": "Turun tangan", "ex": "The manager stepped in to resolve the conflict." },
    { "word": "Patch up", "pronounce": "pach ap", "def": "Memperbaiki hubungan", "ex": "They patched up their differences." },
    { "word": "Talk over", "pronounce": "tok o-ver", "def": "Mendiskusikan", "ex": "Let's talk over the problem." },
    { "word": "Think through", "pronounce": "think thru", "def": "Memikirkan matang-matang", "ex": "You need to think through your decision." },
    { "word": "Bounce back", "pronounce": "bauns bak", "def": "Bangkit kembali", "ex": "He bounced back from his failure." },
    { "word": "Nail down", "pronounce": "neyl daun", "def": "Memastikan", "ex": "We need to nail down the details." },
    { "word": "Iron out", "pronounce": "ai-ern aut", "def": "Menyelesaikan masalah kecil", "ex": "We ironed out the small issues." },
    { "word": "Smooth over", "pronounce": "smuth o-ver", "def": "Merapikan konflik", "ex": "She smoothed over the argument." },
    { "word": "Rally around", "pronounce": "ra-li a-raund", "def": "Bersatu mendukung", "ex": "The community rallied around them." },
    { "word": "See to", "pronounce": "si tu", "def": "Mengurus", "ex": "I'll see to the matter personally." }
  ]
},{
  "name": "Bisnis",
  "items": [
    { "word": "Carry out", "pronounce": "ka-ri aut", "def": "Melaksanakan", "ex": "We need to carry out the plan." },
    { "word": "Set up", "pronounce": "set ap", "def": "Mendirikan", "ex": "They set up a new company." },
    { "word": "Lay off", "pronounce": "ley of", "def": "Memberhentikan kerja", "ex": "The company laid off 50 workers." },
    { "word": "Follow up", "pronounce": "fo-lo ap", "def": "Menindaklanjuti", "ex": "I need to follow up on the email." },
    { "word": "Run out of", "pronounce": "ran aut of", "def": "Kehabisan", "ex": "We ran out of office supplies." },
    { "word": "Deal with", "pronounce": "dil with", "def": "Menangani", "ex": "She deals with customer complaints." },
    { "word": "Look into", "pronounce": "luk in-tu", "def": "Menyelidiki", "ex": "We'll look into the problem." },
    { "word": "Work on", "pronounce": "werk on", "def": "Mengerjakan", "ex": "I'm working on a new project." },
    { "word": "Sign off", "pronounce": "sain of", "def": "Menyetujui", "ex": "The manager signed off on the budget." },
    { "word": "Clock in", "pronounce": "klok in", "def": "Absen masuk", "ex": "Don't forget to clock in." },
    { "word": "Clock out", "pronounce": "klok aut", "def": "Absen pulang", "ex": "I clocked out at 5 PM." },
    { "word": "Take on", "pronounce": "teyk on", "def": "Menerima tanggung jawab", "ex": "She took on a new role." },
    { "word": "Hand over", "pronounce": "hand o-ver", "def": "Menyerahkan", "ex": "He handed over the files." },
    { "word": "Step down", "pronounce": "step daun", "def": "Mengundurkan diri", "ex": "The CEO stepped down." },
    { "word": "Fill in for", "pronounce": "fil in for", "def": "Menggantikan sementara", "ex": "I'm filling in for my colleague." },
    { "word": "Kick off", "pronounce": "kik of", "def": "Memulai (proyek)", "ex": "We kicked off the project yesterday." },
    { "word": "Wrap up", "pronounce": "rap ap", "def": "Menyelesaikan", "ex": "Let's wrap up the meeting." },
    { "word": "Push back", "pronounce": "push bak", "def": "Menunda", "ex": "They pushed back the deadline." },
    { "word": "Scale up", "pronounce": "skeyl ap", "def": "Meningkatkan skala", "ex": "We need to scale up production." },
    { "word": "Phase out", "pronounce": "feys aut", "def": "Menghentikan bertahap", "ex": "The old system is being phased out." },
    { "word": "Head up", "pronounce": "hed ap", "def": "Memimpin", "ex": "She heads up the marketing team." },
    { "word": "Liaise with", "pronounce": "li-eyz with", "def": "Berkoordinasi dengan", "ex": "We liaise with other departments." }
  ]
},{
  "name": "Pergaulan",
  "items": [
    { "word": "Hang out", "pronounce": "hang aut", "def": "Nongkrong", "ex": "Let's hang out at the mall." },
    { "word": "Get together", "pronounce": "get to-ge-ther", "def": "Berkumpul", "ex": "We get together every weekend." },
    { "word": "Drift apart", "pronounce": "drift a-part", "def": "Menjauh secara emosional", "ex": "We drifted apart after high school." },
    { "word": "Stick with", "pronounce": "stik with", "def": "Tetap bersama", "ex": "I'll stick with you through everything." },
    { "word": "Look up to", "pronounce": "luk ap tu", "def": "Mengagumi", "ex": "I look up to my older sister." },
    { "word": "Fall out with", "pronounce": "fol aut with", "def": "Bertengkar dengan", "ex": "She fell out with her best friend." },
    { "word": "Make up with", "pronounce": "meyk ap with", "def": "Berdamai kembali", "ex": "They made up with each other." },
    { "word": "Stick up for", "pronounce": "stik ap for", "def": "Membela", "ex": "He always sticks up for his friends." },
    { "word": "Tag along", "pronounce": "tag a-long", "def": "Ikut tanpa diundang", "ex": "Can I tag along with you guys?" },
    { "word": "Ask out", "pronounce": "ask aut", "def": "Mengajak keluar", "ex": "He finally asked her out." },
    { "word": "Mingle", "pronounce": "ming-gel", "def": "Berbaur", "ex": "She mingled with the guests." },
    { "word": "Take in", "pronounce": "teyk in", "def": "Menerima", "ex": "They took her in like family." },
    { "word": "Kick out", "pronounce": "kik aut", "def": "Mengusir", "ex": "He was kicked out of the club." },
    { "word": "Root for", "pronounce": "rut for", "def": "Mendukung", "ex": "I'm rooting for you." },
    { "word": "Bond with", "pronounce": "bond with", "def": "Menjadi dekat", "ex": "He bonded with his new teammates." },
    { "word": "Side with", "pronounce": "said with", "def": "Berpihak", "ex": "I always side with my brother." },
    { "word": "Shut out", "pronounce": "shat aut", "def": "Mengabaikan", "ex": "She shut everyone out." },
    { "word": "Invite over", "pronounce": "in-vait o-ver", "def": "Mengundang", "ex": "We invited our neighbors over." },
    { "word": "Stop by", "pronounce": "stop bai", "def": "Mampir", "ex": "I'll stop by your house later." },
    { "word": "Walk out on", "pronounce": "wok aut on", "def": "Meninggalkan", "ex": "He walked out on his family." },
    { "word": "Fit in with", "pronounce": "fit in with", "def": "Menyesuaikan diri", "ex": "She fits in with the group." },
    { "word": "Come over", "pronounce": "kam o-ver", "def": "Berkunjung", "ex": "Why don't you come over?" },
    { "word": "Pal up with", "pronounce": "pal ap with", "def": "Berteman", "ex": "He palled up with his new classmates." },
    { "word": "Part ways", "pronounce": "part weys", "def": "Berpisah", "ex": "They parted ways after college." }
  ]
},{
  "name": "Sekolah",
  "items": [
    { "word": "Hand in", "pronounce": "hand in", "def": "Menyerahkan tugas", "ex": "Don't forget to hand in your assignment." },
    { "word": "Take notes", "pronounce": "teyk nots", "def": "Mencatat", "ex": "She takes notes during class." },
    { "word": "Go over", "pronounce": "go o-ver", "def": "Meninjau ulang", "ex": "Let's go over the lesson again." },
    { "word": "Drop out", "pronounce": "drop aut", "def": "Keluar dari sekolah", "ex": "He decided to drop out of school." },
    { "word": "Write down", "pronounce": "rait daun", "def": "Menuliskan", "ex": "Write down the important points." },
    { "word": "Read through", "pronounce": "rid thru", "def": "Membaca keseluruhan", "ex": "I read through the entire chapter." },
    { "word": "Catch on", "pronounce": "kec on", "def": "Memahami", "ex": "The students caught on quickly." },
    { "word": "Fill in", "pronounce": "fil in", "def": "Mengisi formulir", "ex": "Please fill in the form." },
    { "word": "Study up on", "pronounce": "sta-di ap on", "def": "Mempelajari", "ex": "I need to study up on biology." },
    { "word": "Sign up for", "pronounce": "sain ap for", "def": "Mengikuti kelas", "ex": "She signed up for the English course." },
    { "word": "Work on", "pronounce": "werk on", "def": "Mengerjakan soal", "ex": "I'm working on the math problems." },
    { "word": "Learn by heart", "pronounce": "lern bai hart", "def": "Menghafal", "ex": "You need to learn this formula by heart." },
    { "word": "Look into", "pronounce": "luk in-tu", "def": "Meneliti", "ex": "I'll look into this topic further." },
    { "word": "Go back over", "pronounce": "go bak o-ver", "def": "Mengulang pelajaran", "ex": "Let's go back over the last chapter." },
    { "word": "Copy from", "pronounce": "ko-pi from", "def": "Menyontek", "ex": "He copied from his friend during the test." },
    { "word": "Ask a question", "pronounce": "ask a kwes-chen", "def": "Mengajukan pertanyaan", "ex": "Please ask a question if you don't understand." },
    { "word": "Explain again", "pronounce": "eks-pleyn a-gen", "def": "Menjelaskan kembali", "ex": "Could you explain it again?" },
    { "word": "Do homework", "pronounce": "du hom-werk", "def": "Mengerjakan PR", "ex": "I do homework after dinner." },
    { "word": "Study together", "pronounce": "sta-di to-ge-ther", "def": "Belajar kelompok", "ex": "We study together every Saturday." },
    { "word": "Turn in", "pronounce": "tern in", "def": "Mengumpulkan tugas", "ex": "Please turn in your assignments." },
    { "word": "Cross out", "pronounce": "kros aut", "def": "Mencoret", "ex": "Cross out the wrong answer." },
    { "word": "Mark", "pronounce": "mark", "def": "Menandai", "ex": "Mark the important pages." },
    { "word": "Sum up", "pronounce": "sam ap", "def": "Membuat ringkasan", "ex": "Let me sum up the main points." }
  ]
},{
  "name": "Internet",
  "items": [
    { "word": "Log in", "pronounce": "log in", "def": "Masuk ke akun", "ex": "I log in to my account." },
    { "word": "Log out", "pronounce": "log aut", "def": "Keluar dari akun", "ex": "Don't forget to log out." },
    { "word": "Sign up", "pronounce": "sain ap", "def": "Mendaftar", "ex": "I signed up for a new account." },
    { "word": "Shut down", "pronounce": "shat daun", "def": "Mematikan (sistem)", "ex": "Please shut down the computer." },
    { "word": "Plug in", "pronounce": "plag in", "def": "Mencolokkan", "ex": "Plug in the charger." },
    { "word": "Scroll down", "pronounce": "skrol daun", "def": "Gulir ke bawah", "ex": "Scroll down to read more." },
    { "word": "Zoom in", "pronounce": "zum in", "def": "Memperbesar tampilan", "ex": "Zoom in to see the details." },
    { "word": "Zoom out", "pronounce": "zum aut", "def": "Memperkecil tampilan", "ex": "Zoom out to see the whole map." },
    { "word": "Upload", "pronounce": "ap-lod", "def": "Mengunggah", "ex": "I need to upload my photos." },
    { "word": "Download", "pronounce": "daun-lod", "def": "Mengunduh", "ex": "I downloaded the new app." },
    { "word": "Update", "pronounce": "ap-deyt", "def": "Memperbarui", "ex": "Please update the software." },
    { "word": "Delete", "pronounce": "di-let", "def": "Menghapus file", "ex": "Delete the unwanted files." },
    { "word": "Save as", "pronounce": "seyv as", "def": "Menyimpan file", "ex": "Save the document as a PDF." },
    { "word": "Open up", "pronounce": "o-pen ap", "def": "Membuka aplikasi", "ex": "Open up the app." },
    { "word": "Close out", "pronounce": "klos aut", "def": "Menutup aplikasi", "ex": "Close out all the windows." },
    { "word": "Reset", "pronounce": "ri-set", "def": "Menyetel ulang", "ex": "Reset your password." },
    { "word": "Type in", "pronounce": "taip in", "def": "Mengetik", "ex": "Type in your username." },
    { "word": "Search for", "pronounce": "serch for", "def": "Mencari di internet", "ex": "I search for the information online." },
    { "word": "Press", "pronounce": "pres", "def": "Menekan tombol", "ex": "Press the enter key." },
    { "word": "Connect to", "pronounce": "ko-nekt tu", "def": "Menyambungkan ke Wi-Fi", "ex": "Connect to the Wi-Fi network." },
    { "word": "Disconnect from", "pronounce": "dis-ko-nekt from", "def": "Memutuskan sambungan", "ex": "Disconnect from the VPN." },
    { "word": "Scan", "pronounce": "skan", "def": "Memindai kode QR", "ex": "Scan the QR code." }
  ]
},{
  "name": "Travel",
  "items": [
    { "word": "Check in", "pronounce": "cek in", "def": "Mendaftar hotel/bandara", "ex": "We need to check in at the airport." },
    { "word": "Check out", "pronounce": "cek aut", "def": "Keluar dari hotel", "ex": "We checked out of the hotel at noon." },
    { "word": "Set off", "pronounce": "set of", "def": "Berangkat", "ex": "We set off early in the morning." },
    { "word": "Get on", "pronounce": "get on", "def": "Naik kendaraan", "ex": "I get on the bus at 7 AM." },
    { "word": "Get off", "pronounce": "get of", "def": "Turun kendaraan", "ex": "We get off at the next stop." },
    { "word": "Drop off", "pronounce": "drop of", "def": "Mengantar", "ex": "He dropped me off at the airport." },
    { "word": "Put off", "pronounce": "put of", "def": "Menunda perjalanan", "ex": "They put off their trip." },
    { "word": "Take off", "pronounce": "teyk of", "def": "Lepas landas", "ex": "The plane takes off at 9 AM." },
    { "word": "Get away", "pronounce": "get a-wey", "def": "Pergi berlibur", "ex": "We want to get away this weekend." },
    { "word": "Touch down", "pronounce": "tach daun", "def": "Mendarat", "ex": "The plane touched down safely." },
    { "word": "Travel around", "pronounce": "tra-vel a-raund", "def": "Bepergian", "ex": "I love to travel around the world." },
    { "word": "Explore around", "pronounce": "eks-plor a-raund", "def": "Menjelajah", "ex": "We explored around the old city." },
    { "word": "Stay over", "pronounce": "stey o-ver", "def": "Menginap", "ex": "We stayed over at my aunt's house." },
    { "word": "Sail off", "pronounce": "seyl of", "def": "Berlayar", "ex": "The ship sailed off at dawn." },
    { "word": "Drive off", "pronounce": "draiv of", "def": "Berkendara", "ex": "They drove off after breakfast." },
    { "word": "Fly out", "pronounce": "flai aut", "def": "Terbang", "ex": "We fly out tomorrow morning." },
    { "word": "Arrive at", "pronounce": "a-raiv at", "def": "Tiba", "ex": "We arrived at the hotel at 3 PM." },
    { "word": "Head back", "pronounce": "hed bak", "def": "Berangkat kembali", "ex": "We headed back home after the tour." },
    { "word": "Go along", "pronounce": "go a-long", "def": "Menyusuri", "ex": "We went along the river." },
    { "word": "Stop over", "pronounce": "stop o-ver", "def": "Singgah", "ex": "We stopped over in Singapore." },
    { "word": "Cross over", "pronounce": "kros o-ver", "def": "Menyeberang", "ex": "We crossed over the bridge." }
  ]
}
];