var slangData = [
{
  "name": "Istilah",
  "items": [
    { "word": "Don't mess with me", "pronounce": "dont mes with mi", "def": "Jangan main-main denganku", "ex": "Don't mess with me, I'm serious." },
    { "word": "Just drop it", "pronounce": "jast drop it", "def": "Lupakan saja", "ex": "Just drop it, we don't need to talk about it." },
    { "word": "It's a wrap", "pronounce": "its a rap", "def": "Sudah selesai", "ex": "That's a wrap, we're done filming." },
    { "word": "Watch your six", "pronounce": "woch yor siks", "def": "Di belakangmu", "ex": "Watch your six, someone's following you." },
    { "word": "Gotta run", "pronounce": "ga-ta ran", "def": "Harus pergi", "ex": "Sorry, gotta run, I'm late." },
    { "word": "Anyway", "pronounce": "en-i-wey", "def": "Ngomong-ngomong", "ex": "Anyway, I should get going." },
    { "word": "Get my drift?", "pronounce": "get mai drift", "def": "Paham maksudnya?", "ex": "Do you get my drift?" },
    { "word": "Forget it", "pronounce": "for-get it", "def": "Sudahlah", "ex": "Forget it, it's not important." },
    { "word": "Get off my back", "pronounce": "get of mai bak", "def": "Berhenti menggangguku", "ex": "Get off my back, I'm doing my best!" },
    { "word": "I'll catch you later", "pronounce": "ail kech yu ley-ter", "def": "Nanti aku menyusul", "ex": "I'll catch you later, bye." },
    { "word": "Fingers crossed", "pronounce": "fing-gers krost", "def": "Semoga berhasil", "ex": "Fingers crossed for your exam!" },
    { "word": "Hasta la vista, baby", "pronounce": "has-ta la vis-ta, bey-bi", "def": "Selamat tinggal", "ex": "Hasta la vista, baby! See you." },
    { "word": "Spit it out", "pronounce": "spit it aut", "def": "Cepat katakan", "ex": "Spit it out, I don't have all day." },
    { "word": "Snap out of it", "pronounce": "snap aut of it", "def": "Sadarlah", "ex": "Snap out of it, you need to focus." },
    { "word": "Gimme", "pronounce": "gi-mi", "def": "Beri aku", "ex": "Gimme that book." },
    { "word": "Vibe check", "pronounce": "vaib cek", "def": "Bagaimana suasananya?", "ex": "Vibe check, are you okay?" },
    { "word": "In a funk", "pronounce": "in a fank", "def": "Depresi", "ex": "I've been in a funk all week." },
    { "word": "In the pink", "pronounce": "in the pink", "def": "Sehat", "ex": "I feel in the pink today." },
    { "word": "Chill out", "pronounce": "chil aut", "def": "Tenang", "ex": "Just chill out, everything is fine." },
    { "word": "Ants in your pants", "pronounce": "ants in yor pants", "def": "Gelisah", "ex": "You have ants in your pants today." },
    { "word": "Don't have kittens", "pronounce": "dont hav ki-tens", "def": "Jangan gugup", "ex": "Don't have kittens, it's not a big deal." },
    { "word": "Brass monkeys", "pronounce": "bras man-kis", "def": "Sangat dingin", "ex": "It's brass monkeys outside today." },
    { "word": "Back on your feet", "pronounce": "bak on yor fit", "def": "Baru sembuh", "ex": "He's back on his feet after the illness." },
    { "word": "One foot in the grave", "pronounce": "wan fut in the greyv", "def": "Sekarat", "ex": "He looks like he has one foot in the grave." },
    { "word": "Cold feet", "pronounce": "kold fit", "def": "Takut", "ex": "I got cold feet before my speech." },
    { "word": "I'm in hot water", "pronounce": "aim in hot wo-ter", "def": "Aku dalam masalah", "ex": "I'm in hot water with my boss." },
    { "word": "Savage", "pronounce": "sa-vij", "def": "Ganas / Keren tanpa ampun", "ex": "That comeback was savage!" },
    { "word": "FOMO", "pronounce": "fo-mo", "def": "Takut ketinggalan", "ex": "I have FOMO when I stay home." },
    { "word": "Dinosaur", "pronounce": "dai-no-sor", "def": "Sangat tua", "ex": "That computer is a dinosaur." },
    { "word": "Salty", "pronounce": "sol-ti", "def": "Kesal", "ex": "Why are you so salty today?" },
    { "word": "Ace", "pronounce": "eys", "def": "Hebat", "ex": "You're an ace at this game." },
    { "word": "Egghead", "pronounce": "eg-hed", "def": "Orang pandai", "ex": "He's a real egghead." },
    { "word": "Dude", "pronounce": "dud", "def": "Bung", "ex": "Hey dude, what's up?" },
    { "word": "Kip", "pronounce": "kip", "def": "Tidur singkat", "ex": "I need a kip before we go out." },
    { "word": "Mug", "pronounce": "mag", "def": "Wajah", "ex": "Look at that ugly mug." },
    { "word": "Boujee", "pronounce": "bu-zhi", "def": "Mewah", "ex": "That restaurant is so boujee." },
    { "word": "Shook", "pronounce": "shuk", "def": "Tertegun", "ex": "I'm shook by the news." }
  ]
},{
  "name": "Istilah 2",
  "items": [
    { "word": "Clout", "pronounce": "klaut", "def": "Pengaruh, kepopuleran", "ex": "He only cares about clout." },
    { "word": "Snack", "pronounce": "snak", "def": "Orang yang sangat menarik secara fisik", "ex": "She's a total snack." },
    { "word": "Gucci", "pronounce": "gu-chi", "def": "Baik, keren", "ex": "Everything is Gucci." },
    { "word": "Squad", "pronounce": "skwod", "def": "Kelompok teman dekat", "ex": "My squad is the best." },
    { "word": "Lit", "pronounce": "lit", "def": "Seru, menyenangkan", "ex": "The party was lit!" },
    { "word": "Fishy", "pronounce": "fi-shi", "def": "Mencurigakan", "ex": "Something is fishy here." },
    { "word": "Blow chunks", "pronounce": "blo chanks", "def": "Muntah", "ex": "He blew chunks after eating that." },
    { "word": "Burn out", "pronounce": "bern aut", "def": "Capek sekali", "ex": "I'm completely burned out." },
    { "word": "Buy the farm", "pronounce": "bai the farm", "def": "Mati", "ex": "He almost bought the farm." },
    { "word": "Gobsmacked", "pronounce": "gob-smakt", "def": "Terpukau, tidak menyangka", "ex": "I was gobsmacked by the news." },
    { "word": "Hillbilly", "pronounce": "hil-bi-li", "def": "Orang udik / norak", "ex": "He talks like a hillbilly." },
    { "word": "I'm sweating like a pig", "pronounce": "aim swet-ing laik a pig", "def": "Aku berkeringat", "ex": "I'm sweating like a pig after that run." },
    { "word": "I'm stuck on her", "pronounce": "aim stak on her", "def": "Aku tergila-gila padanya", "ex": "I'm stuck on her, I can't stop thinking about her." },
    { "word": "Hit the spot", "pronounce": "hit the spot", "def": "Pas sekali, memuaskan", "ex": "That coffee really hit the spot." },
    { "word": "He is a fox", "pronounce": "hi iz a foks", "def": "Dia ganteng", "ex": "He is a fox, isn't he?" },
    { "word": "Lost the plot", "pronounce": "lost the plot", "def": "Kehilangan akal / kacau", "ex": "He's lost the plot completely." },
    { "word": "Lurgy", "pronounce": "ler-gi", "def": "Tidak enak badan", "ex": "I've caught the lurgy." },
    { "word": "Zit face / pizza face", "pronounce": "zit feys / pit-sa feys", "def": "Wajah berjerawat", "ex": "He's got a pizza face." },
    { "word": "Zonked", "pronounce": "zonkt", "def": "Amat sangat lelah", "ex": "I'm absolutely zonked." },
    { "word": "Sod it", "pronounce": "sod it", "def": "Sialan / sudahlah", "ex": "Sod it, I don't care anymore." },
    { "word": "Party-pooper", "pronounce": "par-ti pu-per", "def": "Perusak pesta", "ex": "Don't be a party-pooper!" },
    { "word": "Dish out", "pronounce": "dish aut", "def": "Melontarkan (kritik/pukulan)", "ex": "He can dish out insults." },
    { "word": "Gimme five", "pronounce": "gi-mi faiv", "def": "Tos", "ex": "Gimme five, buddy!" },
    { "word": "Catch someone red-handed", "pronounce": "kec sam-wan red-han-ded", "def": "Menangkap basah seseorang", "ex": "She caught him red-handed." },
    { "word": "Have a punch up with someone", "pronounce": "hav a panch ap with sam-wan", "def": "Berkelahi dengan seseorang", "ex": "He had a punch up with his rival." },
    { "word": "Hit the road", "pronounce": "hit the rod", "def": "Meninggalkan rumah / berangkat", "ex": "We should hit the road now." },
    { "word": "Pipe down", "pronounce": "paip daun", "def": "Diam", "ex": "Pipe down and let me think." },
    { "word": "Cap", "pronounce": "kap", "def": "Kebohongan", "ex": "That's cap, I don't believe you." },
    { "word": "No cap", "pronounce": "no kap", "def": "Sungguhan / jujur", "ex": "No cap, that's the truth." },
    { "word": "Bad egg", "pronounce": "bad eg", "def": "Pembuat onar / orang jahat", "ex": "He's a bad egg, stay away." },
    { "word": "Dodgy", "pronounce": "do-ji", "def": "Mencurigakan / ilegal", "ex": "That deal sounds dodgy." }
  ]
},{
  "name": "Istilah 3",
  "items": [
    { "word": "No hassle", "pronounce": "no ha-sel", "def": "Tidak repot", "ex": "It's no hassle, I can do it." },
    { "word": "On about", "pronounce": "on a-baut", "def": "Membahas / membicarakan", "ex": "What are you on about?" },
    { "word": "Jam sandwich", "pronounce": "jam sand-wich", "def": "Mobil polisi (British slang)", "ex": "Look, it's a jam sandwich!" },
    { "word": "Get a clue", "pronounce": "get a klu", "def": "Pahamilah situasinya / Gunakan akal sehatmu", "ex": "Get a clue, it's obvious!" },
    { "word": "To bail", "pronounce": "tu beyl", "def": "Pergi tiba-tiba / membatalkan janji", "ex": "He bailed on me at the last minute." },
    { "word": "Buck", "pronounce": "bak", "def": "Dolar", "ex": "That costs fifty bucks." },
    { "word": "By the skin of my teeth", "pronounce": "bai the skin of mai tith", "def": "Hampir saja / nyaris", "ex": "I passed by the skin of my teeth." },
    { "word": "Creep", "pronounce": "krip", "def": "Orang yang aneh/menyeramkan", "ex": "That guy is a creep." },
    { "word": "For real", "pronounce": "for ril", "def": "Sungguhan / sebenarnya", "ex": "For real? That's amazing!" },
    { "word": "To get busted", "pronounce": "tu get bas-ted", "def": "Tertangkap", "ex": "We got busted by the police." },
    { "word": "To have a blast", "pronounce": "tu hav a blast", "def": "Bersenang-senang banget", "ex": "We had a blast at the concert." },
    { "word": "Epic fail", "pronounce": "e-pik feyl", "def": "Gagal total", "ex": "That was an epic fail!" },
    { "word": "Goof off", "pronounce": "guf of", "def": "Bermain-main / buang waktu", "ex": "Stop goofing off and work!" },
    { "word": "Cold shoulder", "pronounce": "kold shol-der", "def": "Cuekin / mengabaikan", "ex": "She gave me the cold shoulder." },
    { "word": "To crash", "pronounce": "tu krash", "def": "Tidur pulas cepat / numpang tidur", "ex": "Can I crash at your place tonight?" },
    { "word": "Hangout", "pronounce": "hang-aut", "def": "Nongkrong / tempat nongkrong", "ex": "This is our favorite hangout." },
    { "word": "Feel blue", "pronounce": "fil blu", "def": "Merasa sedih", "ex": "I'm feeling blue today." },
    { "word": "Bored to death", "pronounce": "bord tu deth", "def": "Bosan minta ampun", "ex": "I'm bored to death." },
    { "word": "Back alley", "pronounce": "bak a-li", "def": "Daerah kumuh / gang belakang", "ex": "We found it in a back alley." },
    { "word": "Newbie", "pronounce": "nu-bi", "def": "Pendatang baru / pemula", "ex": "I'm a newbie here." },
    { "word": "High hat", "pronounce": "hai hat", "def": "Sombong / tinggi hati", "ex": "Don't be so high hat." },
    { "word": "Bat out of hell", "pronounce": "bat aut of hel", "def": "Secepat kilat", "ex": "He ran like a bat out of hell." },
    { "word": "Real hunk", "pronounce": "ril hank", "def": "Ganteng banget", "ex": "He's a real hunk." },
    { "word": "Pop the question", "pronounce": "pop the kwes-chen", "def": "Melamar", "ex": "He's going to pop the question tonight." },
    { "word": "Grumpy", "pronounce": "gram-pi", "def": "Cemberut / mudah marah", "ex": "He's always grumpy in the morning." },
    { "word": "Gimme a buzz", "pronounce": "gi-mi a baz", "def": "Telepon aku", "ex": "Gimme a buzz when you get home." },
    { "word": "Rush hour", "pronounce": "rash au-er", "def": "Jam sibuk", "ex": "Traffic is bad during rush hour." },
    { "word": "Gotcha", "pronounce": "go-cha", "def": "Ya, mengerti", "ex": "Gotcha, I understand." },
    { "word": "Clown around", "pronounce": "klaun a-raund", "def": "Melucu / bercanda", "ex": "Stop clowning around!" },
    { "word": "Down in the dumps", "pronounce": "daun in the damps", "def": "Frustrasi / sedih", "ex": "She's down in the dumps lately." },
    { "word": "Lucky dog", "pronounce": "la-ki dog", "def": "Orang yang beruntung", "ex": "You lucky dog!" },
    { "word": "Fatso", "pronounce": "fat-so", "def": "Gembrot (kasar)", "ex": "Don't call him fatso." },
    { "word": "Puppy love", "pronounce": "pa-pi lav", "def": "Cinta monyet", "ex": "It's just puppy love." },
    { "word": "Chicken", "pronounce": "chi-ken", "def": "Penakut", "ex": "Don't be a chicken!" },
    { "word": "Flex", "pronounce": "fleks", "def": "Pamer", "ex": "He's always flexing his new stuff." },
    { "word": "Slay", "pronounce": "sley", "def": "Unggul / keren banget", "ex": "She slayed that performance!" },
    { "word": "Sick", "pronounce": "sik", "def": "Keren, mantap", "ex": "That car is sick!" }
  ]
},{
  "name": "Singkatan",
  "items": [
    { "word": "2day (Today)", "pronounce": "tu-dey", "def": "Hari ini", "ex": "I'm busy 2day, let's meet tomorrow." },
    { "word": "AFAIK (As Far As I Know)", "pronounce": "A-F-A-I-K", "def": "Sepengetahuan saya", "ex": "AFAIK, she hasn't arrived yet." },
    { "word": "AFK (Away From Keyboard)", "pronounce": "A-F-K", "def": "Lagi tidak online", "ex": "I'll be AFK for a few minutes." },
    { "word": "AKA (Also Known As)", "pronounce": "A-K-A", "def": "Juga dikenal sebagai / alias", "ex": "He's AKA the king of pop." },
    { "word": "ASAP (As Soon As Possible)", "pronounce": "A-S-A-P", "def": "Secepat mungkin", "ex": "Please reply ASAP." },
    { "word": "BBL (Be Back Later)", "pronounce": "B-B-L", "def": "Kembali nanti", "ex": "I'm going out, BBL." },
    { "word": "BBS (Be Back Soon)", "pronounce": "B-B-S", "def": "Segera kembali", "ex": "I need to grab lunch, BBS." },
    { "word": "BF (Boyfriend)", "pronounce": "B-F", "def": "Pacar laki-laki", "ex": "My BF is waiting for me." },
    { "word": "BRB (Be Right Back)", "pronounce": "B-R-B", "def": "Segera kembali", "ex": "BRB, I need to answer the door." },
    { "word": "BTW (By The Way)", "pronounce": "B-T-W", "def": "Ngomong-ngomong", "ex": "BTW, have you seen my keys?" },
    { "word": "Budge Up", "pronounce": "baj ap", "def": "Geser sedikit", "ex": "Can you budge up so I can sit?" },
    { "word": "Bullshit", "pronounce": "bul-sheet", "def": "Omong kosong", "ex": "That's complete bullshit!" },
    { "word": "C'mon (Come on)", "pronounce": "ko-mon", "def": "Ayolah!", "ex": "C'mon, let's go!" },
    { "word": "Catch up", "pronounce": "kec ap", "def": "Menyusul / mengikuti perkembangan", "ex": "Let's catch up over lunch." },
    { "word": "CB (Coffee Break)", "pronounce": "C-B", "def": "Istirahat sebentar", "ex": "Let's take a CB." },
    { "word": "Chin Wag", "pronounce": "chin wag", "def": "Obrolan santai", "ex": "We had a nice chin wag." },
    { "word": "CMIIW (Correct Me If I'm Wrong)", "pronounce": "C-M-I-I-W", "def": "Koreksi kalau aku salah", "ex": "CMIIW, but isn't this wrong?" },
    { "word": "Cray Cray", "pronounce": "krey-krey", "def": "Gila banget", "ex": "This party is cray cray!" },
    { "word": "Crazy about", "pronounce": "krey-zi a-baut", "def": "Tergila-gila pada", "ex": "I'm crazy about her." },
    { "word": "CUL (See You Later)", "pronounce": "C-U-L", "def": "Sampai jumpa lagi", "ex": "I'm leaving now, CUL!" },
    { "word": "CYA / Seeya (See You)", "pronounce": "si-ya", "def": "Sampai jumpa", "ex": "CYA tomorrow!" },
    { "word": "Dig", "pronounce": "dig", "def": "Menyukai sesuatu", "ex": "I dig this song!" },
    { "word": "DIY (Do It Yourself)", "pronounce": "D-I-Y", "def": "Lakukan sendiri", "ex": "I love DIY projects." },
    { "word": "Down", "pronounce": "daun", "def": "Setuju / oke", "ex": "I'm down for that." },
    { "word": "Drop it", "pronounce": "drop it", "def": "Sudahlah / lupakan", "ex": "Just drop it, okay?" },
    { "word": "Dunno (Don't know)", "pronounce": "da-no", "def": "Tidak tahu", "ex": "I dunno what to do." },
    { "word": "EG (Evil Grin)", "pronounce": "E-G", "def": "Senyum jahat", "ex": "She gave me an EG." },
    { "word": "EMSG (Email Message)", "pronounce": "E-M-S-G", "def": "Pesan email", "ex": "I sent you an EMSG." }
  ]
},{
  "name": "Singkatan 2",
  "items": [
    { "word": "FC (Fingers Crossed)", "pronounce": "F-C", "def": "Semoga berhasil", "ex": "FC for your exam!" },
    { "word": "FTBOMH (From The Bottom Of My Heart)", "pronounce": "F-T-B-O-M-H", "def": "Dari lubuk hati", "ex": "FTBOMH, I thank you." },
    { "word": "FWIW (For What It's Worth)", "pronounce": "F-W-I-W", "def": "Sekadar informasi saja", "ex": "FWIW, I think you're right." },
    { "word": "FYI (For Your Information)", "pronounce": "F-Y-I", "def": "Sekadar informasi", "ex": "FYI, the meeting is at 3 PM." },
    { "word": "GAL (Get A Life)", "pronounce": "G-A-L", "def": "Cari kesibukan! (sindiran)", "ex": "Stop complaining, GAL!" },
    { "word": "GBU (God Bless You)", "pronounce": "G-B-U", "def": "Semoga Tuhan memberkatimu", "ex": "GBU, my friend." },
    { "word": "Get off my ass", "pronounce": "get of mai as", "def": "Berhenti ganggu aku", "ex": "Get off my ass, I'm working!" },
    { "word": "Get off my back", "pronounce": "get of mai bak", "def": "Berhenti mengkritik", "ex": "Get off my back, I did my best!" },
    { "word": "Get out of it", "pronounce": "get aut of it", "def": "Sudahlah / jangan bohong", "ex": "Get out of it, I don't believe you." },
    { "word": "Get the drift?", "pronounce": "get the drift", "def": "Ngerti?", "ex": "Do you get the drift?" },
    { "word": "GF (Girlfriend)", "pronounce": "G-F", "def": "Pacar perempuan", "ex": "My GF is coming over." },
    { "word": "GFN (Gone For Now)", "pronounce": "G-F-N", "def": "Pergi dulu", "ex": "I'm GFN, talk later." },
    { "word": "Gimme (Give me)", "pronounce": "gi-mi", "def": "Beri aku", "ex": "Gimme that book." },
    { "word": "GR8 (Great)", "pronounce": "greyt", "def": "Hebat / keren", "ex": "That's GR8 news!" },
    { "word": "GTSY (Glad To See You)", "pronounce": "G-T-S-Y", "def": "Senang bertemu denganmu", "ex": "GTSY!" },
    { "word": "GWS (Get Well Soon)", "pronounce": "G-W-S", "def": "Semoga cepat sembuh", "ex": "GWS, hope you feel better." },
    { "word": "H&K (Hugs And Kisses)", "pronounce": "H-and-K", "def": "Peluk dan cium", "ex": "H&K from me." },
    { "word": "HAGN (Have A Good Night)", "pronounce": "H-A-G-N", "def": "Selamat malam", "ex": "HAGN, sleep well!" },
    { "word": "Hella", "pronounce": "hel-la", "def": "Sangat", "ex": "That's hella cool!" },
    { "word": "HHIS (Hanging Head In Shame)", "pronounce": "H-H-I-S", "def": "Malu sekali", "ex": "HHIS, I made a mistake." },
    { "word": "I'm in deep shit", "pronounce": "aim in dip shit", "def": "Masalah besar (kasar)", "ex": "I'm in deep shit now." },
    { "word": "I'm in hot water", "pronounce": "aim in hot wo-ter", "def": "Sedang kesulitan", "ex": "I'm in hot water with my boss." },
    { "word": "IAE (In Any Event)", "pronounce": "I-A-E", "def": "Bagaimanapun juga", "ex": "IAE, I'll be there." },
    { "word": "IC (I See)", "pronounce": "I-C", "def": "Paham / mengerti", "ex": "IC, now I understand." },
    { "word": "IDK (I Don't Know)", "pronounce": "I-D-K", "def": "Saya tidak tahu", "ex": "IDK where she went." },
    { "word": "IMCO (In My Considered Opinion)", "pronounce": "I-M-C-O", "def": "Menurut pendapat matang saya", "ex": "IMCO, this is the best solution." },
    { "word": "IMHO (In My Humble Opinion)", "pronounce": "I-M-H-O", "def": "Menurut pendapat saya", "ex": "IMHO, he's right." },
    { "word": "IOW (In Other Words)", "pronounce": "I-O-W", "def": "Dengan kata lain", "ex": "IOW, we need to start over." },
    { "word": "IRL (In Real Life)", "pronounce": "I-R-L", "def": "Di kehidupan nyata", "ex": "IRL, she's even prettier." },
    { "word": "ITT (In This Thread)", "pronounce": "I-T-T", "def": "Dalam topik ini", "ex": "ITT, we discuss the issue." }
  ]
},{
  "name": "Singkatan 3",
  "items": [
    { "word": "IWALU (I Will Always Love You)", "pronounce": "I-W-A-L-U", "def": "Aku akan selalu menyayangimu", "ex": "IWALU, no matter what." },
    { "word": "J/J (Just Joking)", "pronounce": "J-J", "def": "Hanya bercanda", "ex": "Don't be mad, it's J/J." },
    { "word": "J/K (Just Kidding)", "pronounce": "J-K", "def": "Hanya bercanda", "ex": "I was just J/K!" },
    { "word": "JMO (Just My Opinion)", "pronounce": "J-M-O", "def": "Hanya pendapatku", "ex": "JMO, but I think it's better." },
    { "word": "JTLYK (Just To Let You Know)", "pronounce": "J-T-L-Y-K", "def": "Cuma biar kamu tahu", "ex": "JTLYK, I'll be late." },
    { "word": "KIT (Keep In Touch)", "pronounce": "K-I-T", "def": "Tetap jaga silaturahmi", "ex": "KIT, okay?" },
    { "word": "KOC (Kiss On Cheek)", "pronounce": "K-O-C", "def": "Cium pipi", "ex": "KOC for you!" },
    { "word": "LHM (Lord Help Me)", "pronounce": "L-H-M", "def": "Ya Tuhan, tolonglah aku", "ex": "LHM, I'm so stressed." },
    { "word": "LMAO (Laughing My Ass Off)", "pronounce": "L-M-A-O", "def": "Ngakak banget", "ex": "That meme made me LMAO!" },
    { "word": "LOL (Laugh Out Loud)", "pronounce": "L-O-L", "def": "Tertawa terbahak-bahak", "ex": "LOL, that was so funny!" },
    { "word": "LTNS (Long Time No See)", "pronounce": "L-T-N-S", "def": "Lama tak berjumpa", "ex": "LTNS, how have you been?" },
    { "word": "LY (Love You)", "pronounce": "L-Y", "def": "Sayang kamu", "ex": "LY, goodnight!" },
    { "word": "MTF (More To Follow)", "pronounce": "M-T-F", "def": "Selanjutnya / menyusul", "ex": "MTF, stay tuned." },
    { "word": "NP (No Problem)", "pronounce": "N-P", "def": "Tidak apa-apa", "ex": "NP, I can help." },
    { "word": "NRN (No Reply Necessary)", "pronounce": "N-R-N", "def": "Tidak perlu dibalas", "ex": "NRN, just read this." },
    { "word": "Nutter", "pronounce": "na-ter", "def": "Orang gila", "ex": "He's a complete nutter." },
    { "word": "OL (Old Lady)", "pronounce": "O-L", "def": "Pacar/istri", "ex": "My OL is waiting for me." },
    { "word": "OM (Old Man)", "pronounce": "O-M", "def": "Pacar/suami", "ex": "My OM is at work." },
    { "word": "OMG (Oh my God!)", "pronounce": "O-M-G", "def": "Ya Tuhan!", "ex": "OMG, I can't believe it!" },
    { "word": "OOT (Out Of Topic)", "pronounce": "O-O-T", "def": "Keluar dari topik", "ex": "Sorry, OOT, but I have to ask." },
    { "word": "OTOH (On The Other Hand)", "pronounce": "O-T-O-H", "def": "Di sisi lain", "ex": "OTOH, it could be worse." },
    { "word": "OTTOMH (Off The Top Of My Head)", "pronounce": "O-T-T-O-M-H", "def": "Dari ingatan saja", "ex": "OTTOMH, I think it's around $50." },
    { "word": "OTW (On The Way)", "pronounce": "O-T-W", "def": "Sedang di jalan", "ex": "I'm OTW, see you soon." },
    { "word": "PM (Private Message)", "pronounce": "P-M", "def": "Pesan pribadi", "ex": "Send me a PM later." },
    { "word": "PMFJI (Pardon Me For Jumping In)", "pronounce": "P-M-F-J-I", "def": "Maaf ikut campur", "ex": "PMFJI, but I have an idea." },
    { "word": "POAHF (Put On A Happy Face)", "pronounce": "P-O-A-H-F", "def": "Pasang muka bahagia", "ex": "POAHF, it'll be okay." },
    { "word": "QT (Cutie)", "pronounce": "kyu-ti", "def": "Manis / imut-imut", "ex": "You're such a QT!" },
    { "word": "ROTFL (Rolling On Floor Laughing)", "pronounce": "R-O-T-F-L", "def": "Tertawa guling-guling", "ex": "That joke made me ROTFL!" },
    { "word": "ROTFLMAO (Rolling On The Floor Laughing My Ass Off)", "pronounce": "R-O-T-F-L-M-A-O", "def": "Ngakak terguling-guling", "ex": "ROTFLMAO, that's hilarious!" },
    { "word": "RSN (Real Soon Now)", "pronounce": "R-S-N", "def": "Secepatnya", "ex": "I'll finish it RSN." }
  ]
},{
  "name": "Singkatan 4",
  "items": [
    { "word": "Salty", "pronounce": "sol-ti", "def": "Kesal / getir", "ex": "Why are you so salty today?" },
    { "word": "Selfie", "pronounce": "self-fi", "def": "Memotret diri sendiri", "ex": "Let's take a selfie together." },
    { "word": "SOT (Short Of Time)", "pronounce": "es-oh-ti", "def": "Waktunya terbatas", "ex": "I'm SOT, let's hurry." },
    { "word": "Spit it out", "pronounce": "spit it aut", "def": "Cepat katakan", "ex": "Spit it out, I'm waiting." },
    { "word": "Sticking my neck out", "pronounce": "stik-ing mai nek aut", "def": "Mengambil risiko", "ex": "I'm sticking my neck out for you." },
    { "word": "Stuck on", "pronounce": "stak on", "def": "Tergila-gila pada", "ex": "She's stuck on that guy." },
    { "word": "LOL (Laugh Out Loud)", "pronounce": "el-oh-el", "def": "Tertawa terbahak-bahak", "ex": "That meme made me LOL." },
    { "word": "SYS (See You Soon)", "pronounce": "es-wai-es", "def": "Sampai jumpa lagi", "ex": "I'll see you later, SYS!" },
    { "word": "TA (Thanks Again)", "pronounce": "ti-ey", "def": "Terima kasih lagi", "ex": "TA for the help." },
    { "word": "TCOY (Take Care Of Yourself)", "pronounce": "ti-si-oh-wai", "def": "Jaga dirimu", "ex": "TCOY, talk to you soon." },
    { "word": "TGIF (Thank God It's Friday)", "pronounce": "ti-ji-ai-ef", "def": "Syukurlah hari Jumat", "ex": "TGIF! Time to relax." },
    { "word": "TIA (Thanks In Advance)", "pronounce": "ti-ai-ey", "def": "Terima kasih sebelumnya", "ex": "TIA for your support." },
    { "word": "TILI (Tell It Like It Is)", "pronounce": "ti-ai-el-ai", "def": "Jujur saja", "ex": "TILI, I don't agree." },
    { "word": "TNT (Till Next Time)", "pronounce": "ti-en-ti", "def": "Sampai suatu saat nanti", "ex": "TNT, take care." },
    { "word": "TOY (Thinking Of You)", "pronounce": "ti-oh-wai", "def": "Mikirin kamu", "ex": "TOY, hope you're doing well." },
    { "word": "TTFN (Ta Ta For Now)", "pronounce": "ti-ti-ef-en", "def": "Da da dulu", "ex": "TTFN, see you later." },
    { "word": "TTYL (Talk To You Later)", "pronounce": "ti-ti-wai-el", "def": "Kita lanjutin nanti", "ex": "I gotta go, TTYL." },
    { "word": "Turn Up", "pronounce": "tern ap", "def": "Bersenang-senang / pesta dimulai", "ex": "Let's turn up tonight!" },
    { "word": "Unreal", "pronounce": "an-ril", "def": "Sangat keren", "ex": "That car is unreal!" },
    { "word": "VIP (Very Important Person)", "pronounce": "vi-ai-pi", "def": "Orang istimewa", "ex": "He's a VIP at the event." },
    { "word": "WB (Welcome Back)", "pronounce": "dab-lyu-bi", "def": "Selamat datang kembali", "ex": "WB, we missed you!" },
    { "word": "WTH (What/Who The Heck)", "pronounce": "dab-lyu-ti-eich", "def": "Astaga! / Apa-apaan ini? (umpatan halus)", "ex": "WTH, is that true?" },
    { "word": "WTF (What/Who The Fuck)", "pronounce": "dab-lyu-ti-ef", "def": "Astaga! / Apa-apaan ini? (umpatan kasar)", "ex": "WTF, I can't believe it!" },
    { "word": "YBS (You'll Be Sorry)", "pronounce": "wai-bi-es", "def": "Kamu akan menyesal", "ex": "YBS if you don't listen." },
    { "word": "YG (Young Gentleman)", "pronounce": "wai-ji", "def": "Para pemuda", "ex": "YG, please behave." },
    { "word": "YL (Young Lady)", "pronounce": "wai-el", "def": "Perempuan muda", "ex": "YL, watch your step." },
    { "word": "YM (Young Man)", "pronounce": "wai-em", "def": "Laki-laki muda", "ex": "YM, you're doing great." }
  ]
}
];